//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceAutomation.AddInSideAdapters
{
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class IOpenSourceAutomationAddInViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, OpenSourceAutomation.Contracts.IOpenSourceAutomationAddInContract
    {
        private OpenSourceAutomation.IOpenSourceAutomationAddIn _view;
        public IOpenSourceAutomationAddInViewToContractAddInAdapter(OpenSourceAutomation.IOpenSourceAutomationAddIn view)
        {
            _view = view;
        }
        public virtual void RunInterface(string pluginName)
        {
            _view.RunInterface(pluginName);
        }
        public virtual void Shutdown()
        {
            _view.Shutdown();
        }
        public virtual void ProcessCommand(OSAE.OSAEMethod method)
        {
            System.Data.DataTable dt = new System.Data.DataTable();
            System.Data.DataRow row; 
            dt.Columns.Add("method_name", typeof(string));
            dt.Columns.Add("object_name", typeof(string));
            dt.Columns.Add("parameter_1", typeof(string));
            dt.Columns.Add("parameter_2", typeof(string));
            dt.Columns.Add("address", typeof(string));
            dt.Columns.Add("object_owner", typeof(string));

            row = dt.NewRow();
            row["method_name"] = method.MethodName;
            row["object_name"] = method.ObjectName;
            row["parameter_1"] = method.Parameter1;
            row["parameter_2"] = method.Parameter2;
            row["address"] = method.Address;
            row["object_owner"] = method.Owner;
            dt.Rows.Add(row);

            _view.ProcessCommand(dt);
        }
        internal OpenSourceAutomation.IOpenSourceAutomationAddIn GetSourceView()
        {
            return _view;
        }
    }
}

