CALL osae_sp_object_type_add ('BLUETOOTH','Bluetooth Plugin','Bluetooth','PLUGIN',1,0,0,1,'Bluetooth Plugin');
CALL osae_sp_object_type_state_add('BLUETOOTH','ON','Running','Bluetooth plugin is running');
CALL osae_sp_object_type_state_add('BLUETOOTH','OFF','Stopped','Bluetooth plugin is stopped');
CALL osae_sp_object_type_event_add('BLUETOOTH','ON','Started','Bluetooth plugin started');
CALL osae_sp_object_type_event_add('BLUETOOTH','OFF','Stopped','Bluetooth plugin stopped');
CALL osae_sp_object_type_method_add('BLUETOOTH','ON','Start','','','','','Start the Bluetooth plugin');
CALL osae_sp_object_type_method_add('BLUETOOTH','OFF','Stop','','','','','Stop the Bluetooth plugin');
CALL osae_sp_object_type_property_add('BLUETOOTH','Scan Interval','Integer','','60',1,1,'How many Seconds in between scans');
CALL osae_sp_object_type_property_add('BLUETOOTH','Discover Length','Integer','','8',0,1,'');
CALL osae_sp_object_type_property_add('BLUETOOTH','Learning Mode','Boolean','','TRUE',1,1,'Automatically create Objects for newly scanned devices');
CALL osae_sp_object_type_property_add('BLUETOOTH','System Plugin','Boolean','','FALSE',0,1,'');
CALL osae_sp_object_type_property_add('BLUETOOTH','Debug','Boolean','','FALSE',0,1,'Use Debug to show extra logs');
CALL osae_sp_object_type_property_add('BLUETOOTH','Trust Level','Integer','','90',0,1,'Trust Level 0-100');
CALL osae_sp_object_type_property_add('BLUETOOTH','Version','String','','',0,1,'Version of the Event Ghost plugin');
CALL osae_sp_object_type_property_add('BLUETOOTH','Author','String','','',0,1,'Author of the Event Ghost plugin');

CALL osae_sp_object_type_add ('BLUETOOTH DEVICE','Bluetooth Device','','THING',0,0,0,1,'Bluetooth Device');
CALL osae_sp_object_type_state_add('BLUETOOTH DEVICE','ON','Here','Device is here');
CALL osae_sp_object_type_state_add('BLUETOOTH DEVICE','OFF','Gone','Device is gone');
CALL osae_sp_object_type_event_add('BLUETOOTH DEVICE','ON','Arrived','Device arrived');
CALL osae_sp_object_type_event_add('BLUETOOTH DEVICE','OFF','Left','Device Left');
CALL osae_sp_object_type_method_add('BLUETOOTH DEVICE','ON','Arriving','','','','','Set Device to here');
CALL osae_sp_object_type_method_add('BLUETOOTH DEVICE','OFF','Leaving','','','','','Set Device to gone');
CALL osae_sp_object_type_property_add('BLUETOOTH DEVICE','Discover Type','String','','',0,0,'');