CALL osae_sp_object_type_add ('RCSTR40','RCS Thermostat control','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','RCSTR40');
CALL osae_sp_object_type_state_add ('OFF','Stopped','RCSTR40');
CALL osae_sp_object_type_event_add ('ON','Started','RCSTR40');
CALL osae_sp_object_type_event_add ('OFF','Stopped','RCSTR40');
CALL osae_sp_object_type_method_add ('ON','Start','RCSTR40','','','','');
CALL osae_sp_object_type_method_add ('OFF','Stop','RCSTR40','','','','');
CALL osae_sp_object_type_property_add ('Computer Name','String','','RCSTR40',0);
CALL osae_sp_object_type_property_add ('Port','Integer','5','RCSTR40',0);
CALL osae_sp_object_type_property_add ('ReceiveAll','Boolean','TRUE','RCSTR40',0);
CALL osae_sp_object_type_add ('THERMOSTAT','Thermostatr','','THERMOSTAT',0,1,0,0);
CALL osae_sp_object_type_state_add ('ON','On','THERMOSTAT');
CALL osae_sp_object_type_state_add ('OFF','Off','THERMOSTAT');
CALL osae_sp_object_type_event_add ('ON','On','THERMOSTAT');
CALL osae_sp_object_type_event_add ('OFF','Off','THERMOSTAT');
CALL osae_sp_object_type_property_add ('Outside Air','Integer','','THERMOSTAT',60);
CALL osae_sp_object_type_property_add ('Zone','Integer','','THERMOSTAT',1);
CALL osae_sp_object_type_property_add ('Set Point','Integer','','THERMOSTAT',70);
CALL osae_sp_object_type_property_add ('Set Point Heat','Integer','','THERMOSTAT',70);
CALL osae_sp_object_type_property_add ('Set Point Cool','Integer','','THERMOSTAT',75);
CALL osae_sp_object_type_property_add ('Mode','String','','THERMOSTAT','O');
CALL osae_sp_object_type_property_add ('Fan Mode','Boolean','','THERMOSTAT',0);
