CALL osae_sp_object_type_add ('RCS-TR40','RCS Thermostat control','','PLUGIN',1,0,0,1,'RCS Thermostat control');
CALL osae_sp_object_type_state_add ('RCS-TR40','ON','Running','RCS Thermostat control is Running');
CALL osae_sp_object_type_state_add ('RCS-TR40','OFF','Stopped','RCS Thermostat control is Stopped');
CALL osae_sp_object_type_event_add ('RCS-TR40','ON','Started','RCS Thermostat control Started');
CALL osae_sp_object_type_event_add ('RCS-TR40','OFF','Stopped','RCS Thermostat control Stopped');
CALL osae_sp_object_type_method_add ('RCS-TR40','ON','Start','','','','','Start the RCS Thermostat control');
CALL osae_sp_object_type_method_add ('RCS-TR40','OFF','Stop','','','','','Stop the RCS Thermostat control');
CALL osae_sp_object_type_property_add ('RCS-TR40','Port','Integer','','5',0,1,'Port');
CALL osae_sp_object_type_property_add ('RCS-TR40','ReceiveAll','Boolean','','TRUE',0,1,'ReceiveAll');
CALL osae_sp_object_type_property_add('RCS-TR40','Version','String','','',0,1,'Version of the RCS-TR40 plugin');
CALL osae_sp_object_type_property_add('RCS-TR40','Author','String','','',0,1,'Author of the RCS-TR40 plugin');
CALL osae_sp_object_type_property_add('RCS-TR40','Trust Level','Integer','','90',0,1,'RCS-TR40 plugin Trust Level');

CALL osae_sp_object_type_add ('THERMOSTAT','Thermostat','','THERMOSTAT',0,1,0,0,'Thermostat');
CALL osae_sp_object_type_state_add ('THERMOSTAT','ON','On','Thermostat');
CALL osae_sp_object_type_state_add ('THERMOSTAT','OFF','Off','Thermostat');
CALL osae_sp_object_type_event_add ('THERMOSTAT','ON','On','Thermostat');
CALL osae_sp_object_type_event_add ('THERMOSTAT','OFF','Off','Thermostat');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Outside Air','Integer','','60',0,0,'Outside Air');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Zone','Integer','','1',0,1,'Zone');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Set Point','Integer','','70',0,0,'Set Point');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Set Point Heat','Integer','','70',0,0,'Set Point Heat');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Set Point Cool','Integer','','75',0,0,'Set Point Cool');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Mode','String','','O',0,0,'Mode');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Fan Mode','Boolean','','FALSE',0,1,'Fan Mode');
