CALL osae_sp_object_type_add ('RCSTR40','RCS Thermostat control','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('RCSTR40','ON','Running');
CALL osae_sp_object_type_state_add ('RCSTR40','OFF','Stopped');
CALL osae_sp_object_type_event_add ('RCSTR40','ON','Started');
CALL osae_sp_object_type_event_add ('RCSTR40','OFF','Stopped');
CALL osae_sp_object_type_method_add ('RCSTR40','ON','Start','','','','');
CALL osae_sp_object_type_method_add ('RCSTR40','OFF','Stop','','','','');
CALL osae_sp_object_type_property_add ('RCSTR40','Port','Integer','','5',0);
CALL osae_sp_object_type_property_add ('RCSTR40','ReceiveAll','Boolean','','TRUE',0);
CALL osae_sp_object_type_property_add ('RCSTR40','Trust Level','Integer','','90',0);
CALL osae_sp_object_type_property_add ('RCSTR40','Version','String','','',0);
CALL osae_sp_object_type_property_add ('RCSTR40','Author','String','','',0);

CALL osae_sp_object_type_add ('THERMOSTAT','Thermostatr','','THERMOSTAT',0,1,0,0);
CALL osae_sp_object_type_state_add ('THERMOSTAT','ON','On');
CALL osae_sp_object_type_state_add ('THERMOSTAT','OFF','Off');
CALL osae_sp_object_type_event_add ('THERMOSTAT','ON','On');
CALL osae_sp_object_type_event_add ('THERMOSTAT','OFF','Off');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Outside Air','Integer','',60,0);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Zone','Integer','',1,0);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Set Point','Integer','',70,0);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Set Point Heat','Integer','',70,0);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Set Point Cool','Integer','',75,0);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Mode','String','','O',0);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Fan Mode','Boolean','','FALSE',0);
