CALL osae_sp_object_type_add ('POWERSHELL','PowerShell Script Processor','','PLUGIN',0,0,0,1);
CALL osae_sp_object_type_state_add ('POWERSHELL','ON','Running');
CALL osae_sp_object_type_state_add ('POWERSHELL','OFF','Stopped');
CALL osae_sp_object_type_event_add ('POWERSHELL','ON','Started');
CALL osae_sp_object_type_event_add ('POWERSHELL','OFF','Stopped');
CALL osae_sp_object_type_method_add ('POWERSHELL','ON','Start','','','','');
CALL osae_sp_object_type_method_add ('POWERSHELL','OFF','Stop','','','','');
CALL osae_sp_object_type_method_add ('POWERSHELL','RUN SCRIPT','RUN SCRIPT','','','','');
CALL osae_sp_script_processor_add ('PowerShell','PowerShell');
CALL osae_sp_object_type_property_add ('POWERSHELL','System Plugin','Boolean','','TRUE',0);
CALL osae_sp_object_type_property_add ('POWERSHELL','Trust Level','Integer','','90',0);
CALL osae_sp_object_type_property_add ('POWERSHELL','Version','String','','',0);
CALL osae_sp_object_type_property_add ('POWERSHELL','Author','String','','',0);