CALL osae_sp_object_type_add ('ONKYO','Onkyo Plugin','','PLUGIN',1,1,0,1);
CALL osae_sp_object_type_state_add ('ONKYO','ON','Running');
CALL osae_sp_object_type_state_add ('ONKYO','OFF','Stopped');
CALL osae_sp_object_type_event_add ('ONKYO','ON','Started');
CALL osae_sp_object_type_event_add ('ONKYO','OFF','Stopped');
CALL osae_sp_object_type_method_add ('ONKYO','ON','Start','','','','');
CALL osae_sp_object_type_method_add ('ONKYO','OFF','Stop','','','','');
CALL osae_sp_object_type_method_add ('ONKYO','SCAN','Scan for Receivers','','','','');
CALL osae_sp_object_type_property_add ('ONKYO','System Plugin','Boolean','','TRUE',0);
CALL osae_sp_object_type_property_add('ONKYO','Trust Level','Integer','','90',0);
CALL osae_sp_object_type_property_add('ONKYO','Version','String','','',0);
CALL osae_sp_object_type_property_add('ONKYO','Author','String','','',0);

CALL osae_sp_object_type_add ('ONKYO RECEIVER','Onkyo Receiver','','ONKYO RECEIVER',0,0,0,1);
CALL osae_sp_object_type_state_add ('ONKYO RECEIVER','ON','On');
CALL osae_sp_object_type_state_add ('ONKYO RECEIVER','OFF','Off');
CALL osae_sp_object_type_event_add ('ONKYO RECEIVER','ON','On');
CALL osae_sp_object_type_event_add ('ONKYO RECEIVER','OFF','Off');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','ON','On','','','','');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','OFF','Standby','','','','');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','MUTE','Mute','','','',''); 
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','UNMUTE','Un-Mute','','','','');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','VOLUME UP','Turn Volume Up','','','','');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','VOLUME DOWN','Turn Volume Down','','','','');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','SET VOLUME','Set Volume','Level','','','');
CALL osae_sp_object_type_property_add ('ONKYO RECEIVER','Communication Type','String','','',0);
CALL osae_sp_object_type_property_add ('ONKYO RECEIVER','Network Port','String','','',0);
CALL osae_sp_object_type_property_add ('ONKYO RECEIVER','IP','Integer','','0.0.0.0',0);
CALL osae_sp_object_type_property_add ('ONKYO RECEIVER','COM Port','Integer','','0',0);