CALL osae_sp_object_type_add ('ONKYO','Onkyo Plugin','','PLUGIN',1,1,0,1,'Onkyo Plugin');
CALL osae_sp_object_type_state_add ('ONKYO','ON','Running','Onkyo Plugin is Running');
CALL osae_sp_object_type_state_add ('ONKYO','OFF','Stopped','Onkyo Plugin is Stopped');
CALL osae_sp_object_type_event_add ('ONKYO','ON','Started','Onkyo Plugin Started');
CALL osae_sp_object_type_event_add ('ONKYO','OFF','Stopped','Onkyo Plugin Stopped');
CALL osae_sp_object_type_method_add ('ONKYO','ON','Start','','','','','Start theOnkyo Plugin');
CALL osae_sp_object_type_method_add ('ONKYO','OFF','Stop','','','','','Stop the Onkyo Plugin');
CALL osae_sp_object_type_method_add ('ONKYO','SCAN','Scan for Receivers','','','','','Scan for Receivers');
CALL osae_sp_object_type_property_add ('ONKYO','System Plugin','Boolean','','TRUE',0,1,'Is Onkyo Plugin a System Plugin');
CALL osae_sp_object_type_property_add('RSS','Version','String','','',0,1,'Version of the RSS plugin');
CALL osae_sp_object_type_property_add('RSS','Author','String','','',0,1,'Author of the RSS plugin');
CALL osae_sp_object_type_property_add('RSS','Trust Level','Integer','','90',0,1,'RSS plugin Trust Level');

CALL osae_sp_object_type_add ('ONKYO RECEIVER','Onkyo Receiver','','ONKYO RECEIVER',0,0,0,1,'Onkyo Receiver');
CALL osae_sp_object_type_state_add ('ONKYO RECEIVER','ON','On','Onkyo Receiver is On');
CALL osae_sp_object_type_state_add ('ONKYO RECEIVER','OFF','Off','Onkyo Receiver is Off');
CALL osae_sp_object_type_event_add ('ONKYO RECEIVER','ON','On','Onkyo Receiver turned On');
CALL osae_sp_object_type_event_add ('ONKYO RECEIVER','OFF','Off','Onkyo Receiver turned Off');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','ON','On','','','','','Turn the Onkyo Receiver On');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','OFF','Standby','','','','','Turn the Onkyo Receiver off');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','MUTE','Mute','','','','','Mute the Onkyo Receiver'); 
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','UNMUTE','Un-Mute','','','','','Un-Mute the Onkyo Receiver');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','VOLUME UP','Turn Volume Up','','','','','Turn Volume Up on the Onkyo Receiver');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','VOLUME DOWN','Turn Volume Down','','','','','Turn Volume Down on the Onkyo Receiver');
CALL osae_sp_object_type_method_add ('ONKYO RECEIVER','SET VOLUME','Set Volume','Level','','','','Set Volume on the Onkyo Receiver');
CALL osae_sp_object_type_property_add ('ONKYO RECEIVER','Communication Type','String','','',0,1,'Communication Type');
CALL osae_sp_object_type_property_add ('ONKYO RECEIVER','Network Port','String','','',0,0,'Network Port');
CALL osae_sp_object_type_property_add ('ONKYO RECEIVER','IP','Integer','','0.0.0.0',0,0,'IP');
CALL osae_sp_object_type_property_add ('ONKYO RECEIVER','COM Port','Integer','','0',0,0,'COM Port');