CALL osae_sp_object_type_add ('INSTEON','Insteon PLM Plugin','Insteon','PLUGIN',1,1,0,1,'Insteon PLM Plugin');
CALL osae_sp_object_type_state_add('INSTEON','ON','Running','Insteon plugin is running');
CALL osae_sp_object_type_state_add('INSTEON','OFF','Stopped','Insteon plugin is stopped');
CALL osae_sp_object_type_event_add('INSTEON','ON','Started','Insteon plugin is started');
CALL osae_sp_object_type_event_add('INSTEON','OFF','Stopped','Insteon plugin is stopped');
CALL osae_sp_object_type_method_add('INSTEON','ON','Start','','','','','Start the Insteon plugin');
CALL osae_sp_object_type_method_add('INSTEON','OFF','Stop','','','','','Stop the Insteon plugin');
CALL osae_sp_object_type_property_add('INSTEON','Port','Integer','','0',0,1,'COM Port number');
CALL osae_sp_object_type_property_add('INSTEON','System Plugin','Boolean','','FALSE',0,1,'System plugin');
CALL osae_sp_object_type_property_add('INSTEON','Debug','Boolean','','FALSE',0,1,'Use Debug to show extra logs');
CALL osae_sp_object_type_property_add('INSTEON','Version','String','','',0,1,'Version of the Insteon plugin');
CALL osae_sp_object_type_property_add('INSTEON','Author','String','','',0,1,'Author of the Insteon plugin');
CALL osae_sp_object_type_property_add('INSTEON','Trust Level','Integer','','90',0,1,'Insteon plugin Trust Level');

CALL osae_sp_object_type_add ('INSTEON DIMMER','Insteon Dimmer','Insteon','SWITCH',0,0,0,0,'Insteon Dimmer');
CALL osae_sp_object_type_state_add('INSTEON DIMMER','ON','On','On');
CALL osae_sp_object_type_state_add('INSTEON DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_event_add('INSTEON DIMMER','ON','On','On');
CALL osae_sp_object_type_event_add('INSTEON DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_method_add('INSTEON DIMMER','ON','On','Dim Level in %','','100','','Turn On');
CALL osae_sp_object_type_method_add('INSTEON DIMMER','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_method_add('INSTEON DIMMER','BRIGHT','Bright','','','','','Bright');
CALL osae_sp_object_type_method_add('INSTEON DIMMER','DIM','Dim','','','','','Dim');
CALL osae_sp_object_type_property_add('INSTEON DIMMER','Off Timer','Integer','','',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('INSTEON DIMMER','Level','Integer','','',0,0,'Dim Level 0-100%');

CALL osae_sp_object_type_add ('INSTEON RELAY','Insteon Relay','Insteon','SWITCH',0,0,0,0,'Insteon Relay');
CALL osae_sp_object_type_state_add('INSTEON RELAY','ON','On','On');
CALL osae_sp_object_type_state_add('INSTEON RELAY','OFF','Off','Off');
CALL osae_sp_object_type_event_add('INSTEON RELAY','ON','On','On');
CALL osae_sp_object_type_event_add('INSTEON RELAY','OFF','Off','Off');
CALL osae_sp_object_type_method_add('INSTEON RELAY','ON','On','Dim Level in %','','100','','Turn On');
CALL osae_sp_object_type_method_add('INSTEON RELAY','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_property_add('INSTEON RELAY','Off Timer','Integer','','',0,1,'# of seconds after activity until device turns off');

CALL osae_sp_object_type_add ('X10 DIMMER','X10 Dimmer','','SWITCH',0,0,0,0,'X10 Dimmer');
CALL osae_sp_object_type_state_add('X10 DIMMER','ON','On','On');
CALL osae_sp_object_type_state_add('X10 DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 DIMMER','ON','On','On');
CALL osae_sp_object_type_event_add('X10 DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_method_add('X10 DIMMER','ON','On','Dim Level in %','','100','','Turn On');
CALL osae_sp_object_type_method_add('X10 DIMMER','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_method_add('X10 DIMMER','BRIGHT','Bright','Increment %','','10','','Bright');
CALL osae_sp_object_type_method_add('X10 DIMMER','DIM','Dim','Decrement %','','10','','Dim');
CALL osae_sp_object_type_property_add('X10 DIMMER','Off Timer','Integer','','-1',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('X10 DIMMER','Level','Integer','','0',0,0,'Dim Level 0-100%');
CALL osae_sp_object_type_property_add('X10 DIMMER','Soft Start','Boolean','','FALSE',0,0,'Soft Start');

CALL osae_sp_object_type_add ('X10 RELAY','X10 Relay','','SWITCH',0,0,0,0,'X10 Relay');
CALL osae_sp_object_type_state_add('X10 RELAY','ON','On','On');
CALL osae_sp_object_type_state_add('X10 RELAY','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 RELAY','ON','On','On');
CALL osae_sp_object_type_event_add('X10 RELAY','OFF','Off','Off');
CALL osae_sp_object_type_method_add('X10 RELAY','ON','On','','','','','Turn On');
CALL osae_sp_object_type_method_add('X10 RELAY','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_property_add('X10 RELAY','Off Timer','Integer','','-1',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('X10 RELAY','Soft Start','Boolean','','FALSE',0,0,'Soft Start');