CALL osae_sp_object_type_add ('SPEECH','Speech plugin','Speech','PLUGIN',1,0,0,1,'Speech plugin');
CALL osae_sp_object_type_state_add('SPEECH','ON','Running','The Speech plugin is Running');
CALL osae_sp_object_type_state_add('SPEECH','OFF','Stopped','The Speech plugin is Stopped!');
CALL osae_sp_object_type_event_add('SPEECH','ON','Started','The Speech plugin was Started');
CALL osae_sp_object_type_event_add('SPEECH','OFF','Stopped','The Speech plugin was Stopped!');
CALL osae_sp_object_type_method_add('SPEECH','ON','On','','','','','Start the Speech plugin');
CALL osae_sp_object_type_method_add('SPEECH','OFF','Off','','','','','Stop the Speech plugin');
CALL osae_sp_object_type_method_add('SPEECH','SPEAK','Say','Message','','Hello','','Say');
CALL osae_sp_object_type_method_add('SPEECH','SPEAKFROM','Say From List','Object Name','Property Name','Speech List','Greetings','Say From List');
CALL osae_sp_object_type_method_add('SPEECH','PLAY','Play','File','','','','Play');
CALL osae_sp_object_type_method_add('SPEECH','PLAYFROM','Play From List','List','','','','Play From List');
CALL osae_sp_object_type_method_add('SPEECH','STOP','Stop','','','','','Stop');
CALL osae_sp_object_type_method_add('SPEECH','PAUSE','Pause','','','','','Pause');
CALL osae_sp_object_type_method_add('SPEECH','MUTEVR','Mute the Microphone','','','','','Mute the Microphone');
CALL osae_sp_object_type_method_add('SPEECH','SETVOICE','Set Voice','Voice','','Anna','','Set Voice');
CALL osae_sp_object_type_method_add('SPEECH','SETTTSRATE','Set TTS Rate','Rate','','0','','Set TTS Rate');
CALL osae_sp_object_type_method_add('SPEECH','SETTTSVOLUME','Set TTS Volume','Volume','','100','','Set TTS Volume');
CALL osae_sp_object_type_property_add('SPEECH','Voice','String','','',0,1,'Voice');
CALL osae_sp_object_type_property_add('SPEECH','Voices','List','','',0,0,'Available Voices');
CALL osae_sp_object_type_property_add('SPEECH','System Plugin','Boolean','','FALSE',0,1,'System Plugin');
CALL osae_sp_object_type_property_add('SPEECH','TTS Rate','Integer','','',0,1,'TTS Rate');
CALL osae_sp_object_type_property_add('SPEECH','TTS Volume','Integer','','',0,1,'TTS Volume');
CALL osae_sp_object_type_property_add('SPEECH','Speaking','Boolean','','FALSE',0,1,'Speaking');
CALL osae_sp_object_type_property_add('SPEECH','Debug','Boolean','','FALSE',0,1,'Debug');
CALL osae_sp_object_type_property_add('SPEECH','Trust Level','Integer','','90',0,1,'Speech Trust Level');
CALL osae_sp_object_type_property_add('SPEECH','Version','String','','',0,1,'Speech plugin Version');
CALL osae_sp_object_type_property_add('SPEECH','Author','String','','',0,1,'Speech plugin Author');
