CALL osae_sp_object_type_add ('COMPUTER POWER','Computer Power Monitor Plugin','Computer Power','PLUGIN',1,0,0,1,'Computer Power Monitor Plugin');
CALL osae_sp_object_type_state_add('COMPUTER POWER','ON','Running','Computer Power Monitor Plugin is Running');
CALL osae_sp_object_type_state_add('COMPUTER POWER','OFF','Stopped','Computer Power Monitor Plugin is Stopped');
CALL osae_sp_object_type_event_add('COMPUTER POWER','ON','Started','Computer Power Monitor Plugin Started');
CALL osae_sp_object_type_event_add('COMPUTER POWER','OFF','Stopped','Computer Power Monitor Plugin Stopped');
CALL osae_sp_object_type_method_add('COMPUTER POWER','ON','Start','','','','','Start the Computer Power Monitor Plugin');
CALL osae_sp_object_type_method_add('COMPUTER POWER','OFF','Stop','','','','','Stop the Computer Power Monitor Plugin');
CALL osae_sp_object_type_method_add('COMPUTER POWER','UPDATE','Update','','','','','Update the Computer Power Monitor data');
CALL osae_sp_object_type_property_add('COMPUTER POWER','Update Interval','Integer','','30',0,1,'Update Interval');
CALL osae_sp_object_type_property_add('COMPUTER POWER','Computer Name','String','','',0,0,'Computer Name');
CALL osae_sp_object_type_property_add('COMPUTER POWER','Version','String','','',0,1,'Version of the Computer Power Monitor plugin');
CALL osae_sp_object_type_property_add('COMPUTER POWER','Author','String','','',0,1,'Author of the Computer Power Monitor plugin');
CALL osae_sp_object_type_property_add('COMPUTER POWER','Trust Level','Integer','','90',0,1,'Computer Power Monitor plugin Trust Level');

CALL osae_sp_object_type_event_add ('COMPUTER','PowerLost','PowerLost','PowerLost');
CALL osae_sp_object_type_event_add ('COMPUTER','PowerRestored','PowerRestored','PowerRestored');
CALL osae_sp_object_type_property_add ('COMPUTER','PowerLineStatus','String','','',0,0,'PowerLineStatus');
CALL osae_sp_object_type_property_add ('COMPUTER','BatteryChargeStatus','String','','',0,0,'BatteryChargeStatus');
CALL osae_sp_object_type_property_add ('COMPUTER','BatteryFullLifeTime','Integer','','',0,0,'BatteryFullLifeTime');
CALL osae_sp_object_type_property_add ('COMPUTER','BatteryLifePercent','Integer','','',0,0,'BatteryLifePercent');
CALL osae_sp_object_type_property_add ('COMPUTER','BatteryLifeRemaining','Integer','','',0,0,'BatteryLifeRemaining');