CALL osae_sp_object_type_add ('SSH','SSH','','PLUGIN',0,1,0,1,'SSH Plugin');
CALL osae_sp_object_type_state_add ('SSH','ON','Running','SSH Plugin is Running');
CALL osae_sp_object_type_state_add ('SSH','OFF','Stopped','SSH Plugin is Stopped');
CALL osae_sp_object_type_event_add ('SSH','ON','Started','SSH Plugin Started');
CALL osae_sp_object_type_event_add ('SSH','OFF','Stopped','SSH Plugin Stopped');
CALL osae_sp_object_type_method_add ('SSH','EXECUTE','Execute Command','Server/Username/Password','Command','','','Execute Command');
CALL osae_sp_object_type_method_add ('SSH','ON','Start','','','','','Start the SSH Plugin');
CALL osae_sp_object_type_method_add ('SSH','OFF','Stop','','','','','Stop the SSH Plugin');
CALL osae_sp_object_type_property_add('SSH','Version','String','','',0,1,'Version of the SSH plugin');
CALL osae_sp_object_type_property_add('SSH','Author','String','','',0,1,'Author of the SSH plugin');
CALL osae_sp_object_type_property_add('SSH','Trust Level','Integer','','90',0,1,'SSH plugin Trust Level');
