CALL osae_sp_object_type_add ('THERMOSTAT','','','THERMOSTAT',1,0,0,1);
CALL osae_sp_object_type_event_add ('THERMOSTAT','HEATON','Heat On');
CALL osae_sp_object_type_event_add ('THERMOSTAT','HEATOFF','Heat Off');
CALL osae_sp_object_type_event_add ('THERMOSTAT','COOLON','Cool On');
CALL osae_sp_object_type_event_add ('THERMOSTAT','COOLOFF','Cool Off');
CALL osae_sp_object_type_event_add ('THERMOSTAT','FANON','Fan On');
CALL osae_sp_object_type_event_add ('THERMOSTAT','FANOFF','Fan Off');
CALL osae_sp_object_type_event_add ('THERMOSTAT','FANOFF','Fan Off');
CALL osae_sp_object_type_event_add ('THERMOSTAT','TEMPCHANGE','Temperature Change');
CALL osae_sp_object_type_event_add ('THERMOSTAT','HEATSPCHANGE','Heat SP Change');
CALL osae_sp_object_type_event_add ('THERMOSTAT','COOLSPCHANGE','Cool SP Change');
CALL osae_sp_object_type_event_add ('THERMOSTAT','FANMODECHANGE','Fan Mode Change');
CALL osae_sp_object_type_method_add ('THERMOSTAT','INIT','Initialize','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','NIGHTSP','Night setpoint','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','DAYSP','Day setpoint','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','HEATSPLOWER','Lower heat setpoint','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','CHECKSTATUS','Check status','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','CHECKTEMP','Check temp','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','COOLSP','Cool Setpoint','Temperature','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','HEATSP','Heat setpoint','Temperature','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','FANON','Fan On Mode','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','FANAUTO','Fan auto mode','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','COOLSPRAISE','Raise cooling setpoint','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','COOLSPLOWER','Lower cooling setpoint','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','HEATSPRAISE','Raise heat setpoint','','','','');
CALL osae_sp_object_type_method_add ('THERMOSTAT','AWAYSP','Away setpoint','','','','');
CALL osae_sp_object_type_property_add ('THERMOSTAT','Temperature','Integer','','0',1);
CALL osae_sp_object_type_property_add ('THERMOSTAT','HeatSP','Integer','','0',1);
CALL osae_sp_object_type_property_add ('THERMOSTAT','CoolSP','Integer','','0',1);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Fan','Boolean','','FALSE',1);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Heating','Boolean','','FALSE',1);
CALL osae_sp_object_type_property_add ('THERMOSTAT','Cooling','Boolean','','TRUE',1);
CALL osae_sp_object_type_property_add ('THERMOSTAT','FanMode','String','','',1);
CALL osae_sp_object_type_property_add ('THERMOSTAT','FilterChange','DateTime','','',0);

CALL osae_sp_object_type_add ('APRILAIRETHERMOSTAT','Aprilaire Thermostat','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('APRILAIRETHERMOSTAT','ON','Running');
CALL osae_sp_object_type_state_add ('APRILAIRETHERMOSTAT','OFF','Stopped');
CALL osae_sp_object_type_event_add ('APRILAIRETHERMOSTAT','ON','Started');
CALL osae_sp_object_type_event_add ('APRILAIRETHERMOSTAT','OFF','Stopped');
CALL osae_sp_object_type_method_add ('APRILAIRETHERMOSTAT','ON','Start','','','','');
CALL osae_sp_object_type_method_add ('APRILAIRETHERMOSTAT','OFF','Stop','','','','');
CALL osae_sp_object_type_property_add ('APRILAIRETHERMOSTAT','IPAddress','String','','',0);
CALL osae_sp_object_type_property_add ('APRILAIRETHERMOSTAT','Port','Integer','','0',0);
