CALL osae_sp_object_type_add ('THERMOSTAT','Thermostat','','THERMOSTAT',1,0,0,1);
CALL osae_sp_object_type_event_add ('HEATON','Heat On','THERMOSTAT');
CALL osae_sp_object_type_event_add ('HEATOFF','Heat Off','THERMOSTAT');
CALL osae_sp_object_type_event_add ('COOLON','Cool On','THERMOSTAT');
CALL osae_sp_object_type_event_add ('COOLOFF','Cool Off','THERMOSTAT');
CALL osae_sp_object_type_event_add ('FANON','Fan On','THERMOSTAT');
CALL osae_sp_object_type_event_add ('FANOFF','Fan Off','THERMOSTAT');
CALL osae_sp_object_type_event_add ('FANOFF','Fan Off','THERMOSTAT');
CALL osae_sp_object_type_event_add ('TEMPCHANGE','Temperature Change','THERMOSTAT');
CALL osae_sp_object_type_event_add ('HEATSPCHANGE','Heat SP Change','THERMOSTAT');
CALL osae_sp_object_type_event_add ('COOLSPCHANGE','Cool SP Change','THERMOSTAT');
CALL osae_sp_object_type_event_add ('FANMODECHANGE','Fan Mode Change','THERMOSTAT');

CALL osae_sp_object_type_method_add ('INIT','Initialize ','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('NIGHTSP','Night setpoint','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('DAYSP','Day setpoint','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('HEATSPLOWER','Lower heat setpoint','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('CHECKSTATUS','Check status','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('CHECKTEMP','Check temp','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('COOLSP','Cool Setpoint','THERMOSTAT','Temperature','','','');
CALL osae_sp_object_type_method_add ('HEATSP','Heat setpoint','THERMOSTAT','Temperature','','','');
CALL osae_sp_object_type_method_add ('FANON','Fan On Mode','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('FANAUTO','Fan auto mode','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('COOLSPRAISE','Raise cooling setpoint','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('COOLSPLOWER','Lower cooling setpoint','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('HEATSPRAISE','Raise heat setpoint','THERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('AWAYSP','Away setpoint','THERMOSTAT','','','','');
CALL osae_sp_object_type_property_add ('Temperature','Integer','','THERMOSTAT',1);
CALL osae_sp_object_type_property_add ('HeatSP','Integer','','THERMOSTAT',1);
CALL osae_sp_object_type_property_add ('CoolSP','Integer','','THERMOSTAT',1);
CALL osae_sp_object_type_property_add ('Fan','Boolean','','THERMOSTAT',1);
CALL osae_sp_object_type_property_add ('Heating','Boolean','','THERMOSTAT',1);
CALL osae_sp_object_type_property_add ('Cooling','Boolean','','THERMOSTAT',1);
CALL osae_sp_object_type_property_add ('FanMode','String','','THERMOSTAT',1);
CALL osae_sp_object_type_property_add ('FilterChange','DateTime','','THERMOSTAT',0);

CALL osae_sp_object_type_add ('APRILAIRETHERMOSTAT','Aprilaire Thermostat','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','APRILAIRETHERMOSTAT');
CALL osae_sp_object_type_state_add ('OFF','Stopped','APRILAIRETHERMOSTAT');
CALL osae_sp_object_type_event_add ('ON','Started','APRILAIRETHERMOSTAT');
CALL osae_sp_object_type_event_add ('OFF','Stopped','APRILAIRETHERMOSTAT');
CALL osae_sp_object_type_method_add ('ON','Start','APRILAIRETHERMOSTAT','','','','');
CALL osae_sp_object_type_method_add ('OFF','Stop','APRILAIRETHERMOSTAT','','','','');
CALL osae_sp_object_type_property_add ('IPAddress','String','','APRILAIRETHERMOSTAT',0);
CALL osae_sp_object_type_property_add ('Port','Integer','','APRILAIRETHERMOSTAT',0);
