CALL osae_sp_object_type_add ('TWITTER','Twitter Plugin','','PLUGIN',1,0,0,1,'Twitter Plugin');
CALL osae_sp_object_type_state_add ('TWITTER','ON','Running','Twitter Plugin is Running');
CALL osae_sp_object_type_state_add ('TWITTER','OFF','Stopped','Twitter Plugin is Stopped');
CALL osae_sp_object_type_event_add ('TWITTER','ON','Started','Twitter Plugin Started');
CALL osae_sp_object_type_event_add ('TWITTER','OFF','Stopped','Twitter Plugin Stopped');
CALL osae_sp_object_type_method_add ('TWITTER','ON','Start','','','','','Start the Twitter Plugin');
CALL osae_sp_object_type_method_add ('TWITTER','OFF','Stop','','','','','Stop the Twitter Plugin');
CALL osae_sp_object_type_method_add ('TWITTER','AUTHENTICATE','Authenticate','','','','','Authenticate');
CALL osae_sp_object_type_method_add ('TWITTER','TWEET','Tweet','Text','','','','Tweet');
CALL osae_sp_object_type_property_add ('TWITTER','Token','String','','',0,0,'Token');
CALL osae_sp_object_type_property_add ('TWITTER','Token Secret','String','','',0,0,'Token Secret');
CALL osae_sp_object_type_property_add ('TWITTER','Pin','String','','',0,0,'Pin');
CALL osae_sp_object_type_property_add ('TWITTER','Auth Token', 'String','','',0,0,'Auth Token');
CALL osae_sp_object_type_property_add ('TWITTER','Version','String','','',0,1,'Version of the Insteon plugin');
CALL osae_sp_object_type_property_add ('TWITTER','Author','String','','',0,1,'Author of the Insteon plugin');
CALL osae_sp_object_type_property_add ('TWITTER','Trust Level','Integer','','90',0,1,'Insteon plugin Trust Level');