CALL osae_sp_object_type_add ('CM17A','CM17A FireCracker','','PLUGIN',1,0,0,1,'CM17A FireCracker');
CALL osae_sp_object_type_state_add ('CM17A','ON','Running','CM17A FireCracker is Running');
CALL osae_sp_object_type_state_add ('CM17A','OFF','Stopped','CM17A FireCracker is Stopped');
CALL osae_sp_object_type_event_add ('CM17A','ON','Started','CM17A FireCracker Started');
CALL osae_sp_object_type_event_add ('CM17A','OFF','Stopped','CM17A FireCracker Stopped');
CALL osae_sp_object_type_method_add ('CM17A','ON','Start','','','','','Start the CM17A FireCracker');
CALL osae_sp_object_type_method_add ('CM17A','OFF','Stop','','','','','Stop the CM17A FireCracker');
CALL osae_sp_object_type_property_add ('CM17A','Port','Integer','1','4',0,1,'COM Port');
CALL osae_sp_object_type_property_add('W800RF','Trust Level','Integer','','90',0,1,'CM17A FireCracker plugin Trust Level');
CALL osae_sp_object_type_property_add('W800RF','Version','String','','',0,1,'Version of the CM17A FireCracker plugin');
CALL osae_sp_object_type_property_add('W800RF','Author','String','','',0,1,'Author of the CM17A FireCracker plugin');

CALL osae_sp_object_type_add ('X10 DIMMER','X10 Dimmer','','SWITCH',0,0,0,0,'X10 Dimmer');
CALL osae_sp_object_type_state_add('X10 DIMMER','ON','On','On');
CALL osae_sp_object_type_state_add('X10 DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 DIMMER','ON','On','On');
CALL osae_sp_object_type_event_add('X10 DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_method_add('X10 DIMMER','ON','On','Dim Level in %','','100','','Turn On');
CALL osae_sp_object_type_method_add('X10 DIMMER','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_method_add('X10 DIMMER','BRIGHT','Bright','Increment %','','10','','Bright');
CALL osae_sp_object_type_method_add('X10 DIMMER','DIM','Dim','Decrement %','','10','','Dim');
CALL osae_sp_object_type_property_add('X10 DIMMER','Off Timer','Integer','','-1',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('X10 DIMMER','Level','Integer','','0',0,0,'Dim Level 0-100%');
CALL osae_sp_object_type_property_add('X10 DIMMER','Soft Start','Boolean','','FALSE',0,0,'Soft Start');

CALL osae_sp_object_type_add ('X10 RELAY','X10 Relay','','SWITCH',0,0,0,0,'X10 Relay');
CALL osae_sp_object_type_state_add('X10 RELAY','ON','On','On');
CALL osae_sp_object_type_state_add('X10 RELAY','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 RELAY','ON','On','On');
CALL osae_sp_object_type_event_add('X10 RELAY','OFF','Off','Off');
CALL osae_sp_object_type_method_add('X10 RELAY','ON','On','','','','','Turn On');
CALL osae_sp_object_type_method_add('X10 RELAY','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_property_add('X10 RELAY','Off Timer','Integer','','-1',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('X10 RELAY','Soft Start','Boolean','','FALSE',0,0,'Soft Start');

CALL osae_sp_object_type_add ('X10 SENSOR','X10 Sensor','','SENSOR',0,0,0,0,'X10 Sensor');
CALL osae_sp_object_type_state_add('X10 SENSOR','ON','On','On');
CALL osae_sp_object_type_state_add('X10 SENSOR','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 SENSOR','ON','On','On');
CALL osae_sp_object_type_event_add('X10 SENSOR','OFF','Off','Off');
CALL osae_sp_object_type_property_add('X10 SENSOR','Off Timer','Integer','','-1',0,1,'Off Timer');
CALL osae_sp_object_type_property_add('X10 SENSOR','Level','Integer','','0',0,0,'Level');

CALL osae_sp_object_type_add ('X10 PHOTOCELL','X10 Photocell','','SENSOR',0,0,0,0,'X10 Photocell');
CALL osae_sp_object_type_state_add('X10 PHOTOCELL','ON','Dark','Dark');
CALL osae_sp_object_type_state_add('X10 PHOTOCELL','OFF','Light','Light');
CALL osae_sp_object_type_event_add('X10 PHOTOCELL','ON','Dark','Dark');
CALL osae_sp_object_type_event_add('X10 PHOTOCELL','OFF','Light','Light');
CALL osae_sp_object_type_property_add('X10 PHOTOCELL','Off Timer','Integer','','-1',0,1,'Off Timer');
CALL osae_sp_object_type_property_add('X10 PHOTOCELL','Level','Integer','','0',1,'Level');