CALL osae_sp_object_type_add ('METER READER','Utility Meter Reader','','PLUGIN',1,0,0,1,'Utility Meter Reader plugin');
CALL osae_sp_object_type_state_add ('METER READER','ON','Running','Utility Meter Reader plugin is Running');
CALL osae_sp_object_type_state_add ('METER READER','OFF','Stopped','Utility Meter Reader plugin is Stopped');
CALL osae_sp_object_type_event_add ('METER READER','ON','Started','Utility Meter Reader plugin Started');
CALL osae_sp_object_type_event_add ('METER READER','OFF','Stopped','Utility Meter Reader plugin Stopped');
CALL osae_sp_object_type_method_add ('METER READER','ON','Start','','','','','Start the Utility Meter Reader plugin');
CALL osae_sp_object_type_method_add ('METER READER','OFF','Stop','','','','','Stop the Utility Meter Reader plugin');
CALL osae_sp_object_type_property_add ('METER READER','Port','Integer','','1',0,1,'Port');
CALL osae_sp_object_type_property_add ('METER READER','ReceiveAll','Boolean','','TRUE',0,1,'ReceiveAll');
CALL osae_sp_object_type_property_add('1WIRE','Version','String','','',0,1,'Version of the 1WIRE plugin');
CALL osae_sp_object_type_property_add('1WIRE','Author','String','','',0,1,'Author of the 1WIRE plugin');
CALL osae_sp_object_type_property_add('1WIRE','Trust Level','Integer','','90',0,1,'1WIRE plugin Trust Level');

CALL osae_sp_object_type_add ('UTILITY METER','Utility Meter','','UTILITY METER',0,1,0,0,'Utility Meter');
CALL osae_sp_object_type_state_add ('UTILITY METER','ON','On','Utility Meter is On');
CALL osae_sp_object_type_state_add ('UTILITY METER','OFF','Off','Utility Meter is Off');
CALL osae_sp_object_type_event_add ('UTILITY METER','ON','On','Utility Meter turned On');
CALL osae_sp_object_type_event_add ('UTILITY METER','OFF','Off','Utility Meter turned Off');
CALL osae_sp_object_type_property_add ('UTILITY METER','Reading','Integer','','0',1,0,'Reading');
CALL osae_sp_object_type_property_add ('UTILITY METER','Rate','Float','','0.0',1,0,'Rate');
CALL osae_sp_object_type_property_add ('UTILITY METER','Type','String','','',0,0,'Type');
