CALL osae_sp_object_type_add ('METER READER','Utility Meter Reader','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','METER READER');
CALL osae_sp_object_type_state_add ('OFF','Stopped','METER READER');
CALL osae_sp_object_type_event_add ('ON','Started','METER READER');
CALL osae_sp_object_type_event_add ('OFF','Stopped','METER READER');
CALL osae_sp_object_type_method_add ('ON','Start','METER READER','','','','');
CALL osae_sp_object_type_method_add ('OFF','Stop','METER READER','','','','');
CALL osae_sp_object_type_property_add ('Computer Name','String','','METER READER',0);
CALL osae_sp_object_type_property_add ('Port','Integer','1','METER READER',0);
CALL osae_sp_object_type_property_add ('ReceiveAll','Boolean','TRUE','METER READER',0);
CALL osae_sp_object_type_add ('UTILITY METER','Utility Meter','','UTILITY METER',0,1,0,0);
CALL osae_sp_object_type_state_add ('ON','On','UTILITY METER');
CALL osae_sp_object_type_state_add ('OFF','Off','UTILITY METER');
CALL osae_sp_object_type_event_add ('ON','On','UTILITY METER');
CALL osae_sp_object_type_event_add ('OFF','Off','UTILITY METER');
CALL osae_sp_object_type_property_add ('Reading','Integer','','UTILITY METER',1);
CALL osae_sp_object_type_property_add ('Rate','Float','','UTILITY METER',1);
CALL osae_sp_object_type_property_add ('Type','String','','UTILITY METER',0);
