CALL osae_sp_object_type_add ('GLOBAL CACHE','Global Cache Plugin','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','GLOBAL CACHE');
CALL osae_sp_object_type_state_add ('OFF','Stopped','GLOBAL CACHE');
CALL osae_sp_object_type_event_add ('ON','Started','GLOBAL CACHE');
CALL osae_sp_object_type_event_add ('OFF','Stopped','GLOBAL CACHE');
CALL osae_sp_object_type_method_add ('ON','Start','GLOBAL CACHE','','','','');
CALL osae_sp_object_type_method_add ('OFF','Stop','GLOBAL CACHE','','','','');


CALL osae_sp_object_type_add ('GC-100','Global Cache GC-100','Global Cache','GC-100',0,0,0,1);
CALL osae_sp_object_type_event_add ('INPUT4:1ON','Input 4:1 On','GC-100');
CALL osae_sp_object_type_event_add ('INPUT4:1OFF','Input 4:1 Off','GC-100');
CALL osae_sp_object_type_event_add ('INPUT4:2ON','Input 4:2 On','GC-100');
CALL osae_sp_object_type_event_add ('INPUT4:2OFF','Input 4:2 Off','GC-100');
CALL osae_sp_object_type_event_add ('INPUT4:3ON','Input 4:3 On','GC-100');
CALL osae_sp_object_type_event_add ('INPUT4:3OFF','Input 4:3 Off','GC-100');
CALL osae_sp_object_type_event_add ('INPUT5:1ON','Input 5:1 On','GC-100');
CALL osae_sp_object_type_event_add ('INPUT5:1OFF','Input 5:1 Off','GC-100');
CALL osae_sp_object_type_event_add ('INPUT5:2ON','Input 5:2 On','GC-100');
CALL osae_sp_object_type_event_add ('INPUT5:2OFF','Input 5:2 Off','GC-100');
CALL osae_sp_object_type_event_add ('INPUT5:3ON','Input 5:3 On','4GC-100');
CALL osae_sp_object_type_event_add ('INPUT5:3OFF','Input 5:3 Off','GC-100');
CALL osae_sp_object_type_method_add ('OUTPUTON','Output On','GC-100','Address','','3:1','');
CALL osae_sp_object_type_method_add ('OUTPUTOFF','Output Off','GC-100','Address','','3:1','');
CALL osae_sp_object_type_property_add ('OUTPUT3:1','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('OUTPUT3:2','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('OUTPUT3:3','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('INPUT4:1','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('INPUT4:2','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('INPUT4:3','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('INPUT5:1','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('INPUT5:2','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('INPUT5:3','Boolean','','GC-100',0);
CALL osae_sp_object_type_property_add ('Model','String','','GC-100',0);
CALL osae_sp_object_type_property_add ('Version','String','','GC-100',0);