CALL osae_sp_object_type_add ('GLOBAL CACHE','Global Cache Plugin','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('GLOBAL CACHE','ON','Running');
CALL osae_sp_object_type_state_add ('GLOBAL CACHE','OFF','Stopped');
CALL osae_sp_object_type_event_add ('GLOBAL CACHE','ON','Started');
CALL osae_sp_object_type_event_add ('GLOBAL CACHE','OFF','Stopped');
CALL osae_sp_object_type_method_add ('GLOBAL CACHE','ON','Start','','','','');
CALL osae_sp_object_type_method_add ('GLOBAL CACHE','OFF','Stop','','','','');
CALL osae_sp_object_type_property_add('GLOBAL CACHE','Trust Level','Integer','','90',0);
CALL osae_sp_object_type_property_add('GLOBAL CACHE','Version','String','','',0);
CALL osae_sp_object_type_property_add('GLOBAL CACHE','Author','String','','',0);

CALL osae_sp_object_type_add ('GC-100','Global Cache GC-100','','Global Cache',0,0,0,1);
CALL osae_sp_object_type_event_add ('GC-100','INPUT4:1ON','Input 4:1 On');
CALL osae_sp_object_type_event_add ('GC-100','INPUT4:1OFF','Input 4:1 Off');
CALL osae_sp_object_type_event_add ('GC-100','INPUT4:2ON','Input 4:2 On');
CALL osae_sp_object_type_event_add ('GC-100','INPUT4:2OFF','Input 4:2 Off');
CALL osae_sp_object_type_event_add ('GC-100','INPUT4:3ON','Input 4:3 On');
CALL osae_sp_object_type_event_add ('GC-100','INPUT4:3OFF','Input 4:3 Off');
CALL osae_sp_object_type_event_add ('GC-100','INPUT5:1ON','Input 5:1 On');
CALL osae_sp_object_type_event_add ('GC-100','INPUT5:1OFF','Input 5:1 Off');
CALL osae_sp_object_type_event_add ('GC-100','INPUT5:2ON','Input 5:2 On');
CALL osae_sp_object_type_event_add ('GC-100','INPUT5:2OFF','Input 5:2 Off');
CALL osae_sp_object_type_event_add ('GC-100','INPUT5:3ON','Input 5:3 On');
CALL osae_sp_object_type_event_add ('GC-100','INPUT5:3OFF','Input 5:3 Off');
CALL osae_sp_object_type_method_add ('GC-100','OUTPUTON','Output On','Address','','3:1','');
CALL osae_sp_object_type_method_add ('GC-100','OUTPUTOFF','Output Off','Address','','3:1','');
CALL osae_sp_object_type_property_add ('GC-100','OUTPUT3:1','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','OUTPUT3:2','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','OUTPUT3:3','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','INPUT4:1','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','INPUT4:2','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','INPUT4:3','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','INPUT5:1','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','INPUT5:2','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','INPUT5:3','Boolean','','FALSE',0);
CALL osae_sp_object_type_property_add ('GC-100','Model','String','','',0);
CALL osae_sp_object_type_property_add ('GC-100','Version','String','','',0);