CALL osae_sp_object_type_add ('WEATHER','Weather Data','','WEATHER',0,1,0,1);
CALL osae_sp_object_type_state_add ('ON','Current','WEATHER');
CALL osae_sp_object_type_state_add ('OFF','Obsolete','WEATHER');
CALL osae_sp_object_type_event_add ('ON','Updated','WEATHER');
CALL osae_sp_object_type_event_add ('OFF','Hung','WEATHER');
CALL osae_sp_object_type_event_add ('DAY','Day','WEATHER');
CALL osae_sp_object_type_event_add ('NIGHT','Night','WEATHER');
CALL osae_sp_object_type_event_add ('DAWN','Dawn','WEATHER');
CALL osae_sp_object_type_event_add ('DUSK','Dusk','WEATHER');
CALL osae_sp_object_type_method_add ('ON','Updated','WEATHER','','','','');
CALL osae_sp_object_type_method_add ('OFF','Hung','WEATHER','','','','');
CALL osae_sp_object_type_property_add ('Night1 Low','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Low','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Low','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Low','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 High','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 High','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 High','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 High','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Conditions','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Wind Speed','Float','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Wind Directions','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Humidity','Integer','','WEATHER',1);
CALL osae_sp_object_type_property_add ('Pressure','Float','','WEATHER',1);
CALL osae_sp_object_type_property_add ('Dewpoint','Float','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Visibility','Float','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Windchill','Integer','','WEATHER',1);
CALL osae_sp_object_type_property_add ('Temp','Float','','WEATHER',1);
CALL osae_sp_object_type_property_add ('Last Updated','DateTime','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 High','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 High','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Low','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Low','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 High','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Low','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today Precip','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Sunrise','DateTime','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Sunset','DateTime','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Low','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today High','Integer','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Latitude','Float','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Logitude','Float','','WEATHER',0);
CALL osae_sp_object_type_property_add ('DayNight','String','','WEATHER',0);


CALL osae_sp_object_type_add ('WUNDERGROUND','Weather Underground','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','WUNDERGROUND');
CALL osae_sp_object_type_state_add ('OFF','Stopped','WUNDERGROUND');
CALL osae_sp_object_type_event_add ('ON','Started','WUNDERGROUND');
CALL osae_sp_object_type_event_add ('OFF','Stopped','WUNDERGROUND');
CALL osae_sp_object_type_method_add ('ON','Start','WUNDERGROUND','','','','');
CALL osae_sp_object_type_method_add ('OFF','Stop','WUNDERGROUND','','','','');
CALL osae_sp_object_type_method_add ('UPDATE','Update','WUNDERGROUND','','','','');
CALL osae_sp_object_type_property_add ('PWS','String','','WUNDERGROUND',0);
CALL osae_sp_object_type_property_add ('Conditions Interval','Integer','5','WUNDERGROUND',0);
CALL osae_sp_object_type_property_add ('Forecast Interval','Integer','60','WUNDERGROUND',0);
CALL osae_sp_object_type_property_add ('Metric','Boolean','False','WUNDERGROUND',0);
CALL osae_sp_object_type_property_add ('DuskPre','Integer','','WUNDERGROUND',0);
CALL osae_sp_object_type_property_add ('DuskPost','Integer','','WUNDERGROUND',0);
CALL osae_sp_object_type_property_add ('DawnPre','Integer','','WUNDERGROUND',0);
CALL osae_sp_object_type_property_add ('DawnPost','Integer','','WUNDERGROUND',0);
