CALL osae_sp_object_type_add ('EMAIL','Email Plugin','Email','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add('EMAIL','ON','Running');
CALL osae_sp_object_type_state_add('EMAIL','OFF','Stopped');
CALL osae_sp_object_type_event_add('EMAIL','ON','Started');
CALL osae_sp_object_type_event_add('EMAIL','OFF','Stopped');
CALL osae_sp_object_type_event_add('EMAIL','EMAIL SENT','Email Sent');
CALL osae_sp_object_type_method_add('EMAIL','ON','Start','','','','');
CALL osae_sp_object_type_method_add('EMAIL','OFF','Stop','','','','');
CALL osae_sp_object_type_method_add('EMAIL','SEND EMAIL','Send Email','TO','Message','','Test Message');
CALL osae_sp_object_type_property_add('EMAIL','SMTP Server','String','','',0);
CALL osae_sp_object_type_property_add('EMAIL','SMTP Port','String','','25',0);
CALL osae_sp_object_type_property_add('EMAIL','ssl','Boolean','','TRUE',0);
CALL osae_sp_object_type_property_add('EMAIL','Username','String','','',0);
CALL osae_sp_object_type_property_add('EMAIL','Password','String','','',0);
CALL osae_sp_object_type_property_add('EMAIL','From Address','String','','',0);
CALL osae_sp_object_type_property_add('EMAIL','System Plugin','Boolean','','TRUE',0);
CALL osae_sp_object_type_property_add('EMAIL','Trust Level','Integer','','90',0);
CALL osae_sp_object_type_property_add('EMAIL','Version','String','','',0);
CALL osae_sp_object_type_property_add('EMAIL','Author','String','','',0);
