CALL osae_sp_object_type_add ('EMAIL','Email Plugin','Email','PLUGIN',1,0,0,1,'Email plugin.');
CALL osae_sp_object_type_state_add('EMAIL','ON','Running','The Email plugin is Running.');
CALL osae_sp_object_type_state_add('EMAIL','OFF','Stopped','The Email plugin is Stopped.');
CALL osae_sp_object_type_event_add('EMAIL','ON','Started','The Email plugin Started.');
CALL osae_sp_object_type_event_add('EMAIL','OFF','Stopped','The Email plugin Stopped.');
CALL osae_sp_object_type_event_add('EMAIL','EMAIL SENT','Email Sent','The Email plugin successfully sent a message.');
CALL osae_sp_object_type_method_add('EMAIL','ON','Start','','','','','Start the Email plugin.');
CALL osae_sp_object_type_method_add('EMAIL','OFF','Stop','','','','','Stop the Email plugin.');
CALL osae_sp_object_type_method_add('EMAIL','SEND EMAIL','Send Email','TO','Message','','Test Message','');
CALL osae_sp_object_type_property_add('EMAIL','SMTP Server','String','','',0,1,'Set the full URL to the SMTP server.');
CALL osae_sp_object_type_property_add('EMAIL','SMTP Port','String','','',0,1,'Set the SMTP Port number.');
CALL osae_sp_object_type_property_add('EMAIL','ssl','Boolean','','TRUE',0,1,'Select True/False if the SMTP server requires SSL encryption.');
CALL osae_sp_object_type_property_add('EMAIL','Username','String','','',0,1,'Enter the Username used to Login to the SMTP server.');
CALL osae_sp_object_type_property_add('EMAIL','Password','String','','',0,1,'Enter the Email Password for the SMTP server.');
CALL osae_sp_object_type_property_add('EMAIL','From Address','String','','',0,1,'Enter the email address Emails will be sent from.');
CALL osae_sp_object_type_property_add('EMAIL','System Plugin','Boolean','','TRUE',0,0,'Is the Email Plugin is a system plugin.');
CALL osae_sp_object_type_property_add('EMAIL','Trust Level','Integer','','90',0,1,'The Trust Level of the Email plugin.');
CALL osae_sp_object_type_property_add('EMAIL','Version','String','','',0,0,'Version of the Email Plugin.');
CALL osae_sp_object_type_property_add('EMAIL','Author','String','','',0,0,'Author of the Email Plugin.');
