CALL osae_sp_object_type_add ('DSC ALARM','DSC Alarm Panel','','PLUGIN',1,0,0,0,'DSC Alarm Panel');
CALL osae_sp_object_type_state_add ('DSC ALARM','ON','Running','DSC Alarm Panel is Running');
CALL osae_sp_object_type_state_add ('DSC ALARM','OFF','Stopped','DSC Alarm Panel is Stopped');
CALL osae_sp_object_type_event_add ('DSC ALARM','ON','Started','DSC Alarm Panel Started');
CALL osae_sp_object_type_event_add ('DSC ALARM','OFF','Stopped','DSC Alarm Panel Stopped');
CALL osae_sp_object_type_property_add ('DSC ALARM','Software Version','String','','',0,0,'Software Version');
CALL osae_sp_object_type_property_add ('DSC ALARM','Baud','Integer','','9600',0,1,'Baud');
CALL osae_sp_object_type_property_add ('DSC ALARM','Update Time','Integer','','60',0,0,'Update Time');
CALL osae_sp_object_type_property_add ('DSC ALARM','Code','Integer','','0',0,0,'Code');
CALL osae_sp_object_type_property_add ('DSC ALARM','Password','String','','',0,0,'Password');
CALL osae_sp_object_type_property_add ('DSC ALARM','Ethernet','Boolean','','FALSE',0,1,'Ethernet');
CALL osae_sp_object_type_property_add ('DSC ALARM','Keybus','String','','',0,0,'Keybus');
CALL osae_sp_object_type_property_add('DSC ALARM','Version','String','','',0,1,'Version of the DSC ALARM plugin');
CALL osae_sp_object_type_property_add('DSC ALARM','Author','String','','',0,1,'Author of the DSC ALARM plugin');
CALL osae_sp_object_type_property_add('DSC ALARM','Trust Level','Integer','','90',0,1,'DSC ALARM plugin Trust Level');

CALL osae_sp_object_type_add ('DSC ALARM PARTITION','DSC Alarm Partition','DSC Alarm','DSC ALARM PARTITION',0,0,0,0,'DSC Alarm Partition');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','READY','Ready','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','NOTREADY','Not Ready','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','ARMEDAWAYNODELAY','Armed - Away, No Delay','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','READYFORCEARMING','Ready for Force Arming','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','INALARM','In Alarm','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','DISARMED','Disarmed','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','EXITDELAYINPROGRESS','Exit Delay In Progress','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','ENTRYDELAYINPROGRESS','Entry Delay In Progress','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','ARMEDAWAY','Armed - Away','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','ARMEDSTAY','Armed - Stay','DSC Alarm Partition is ');
CALL osae_sp_object_type_state_add ('DSC ALARM PARTITION','ARMEDSTAYNODELAY','Armed - Stay, No Delay','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','INALARM','Partition In Alarm','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','ARMEDAWAY','Partition Armed - Away','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','EXITDELAYINPROGRESS','Partition Exit Delay In Progress','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','ENTRYDELAYINPROGRESS','Partition Entry Delay In Progress','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','ARMEDSTAY','Partition Armed - Stay','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','ARMEDAWAYNODELAY','Partition Armed - Away, No Delay','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','ARMEDSTAYNODELAY','Partition Armed - Stay, No Delay','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','READY','Partition Ready','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','NOTREADY','Partition Not Ready','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','DISARMED','Partition Disarmed','DSC Alarm Partition is ');
CALL osae_sp_object_type_event_add ('DSC ALARM PARTITION','READYFORCEARMING','Partition Ready for Forced Arming','DSC Alarm Partition is ');
CALL osae_sp_object_type_method_add('DSC ALARM PARTITION','ARMSTAY','Arm Stay','','','','','DSC Alarm Partition is ');
CALL osae_sp_object_type_method_add('DSC ALARM PARTITION','ARMAWAY','Arm Away','','','','','DSC Alarm Partition is ');
CALL osae_sp_object_type_method_add('DSC ALARM PARTITION','ARMNOENTRYDELAY','Arm No Entry Delay','','','','','DSC Alarm Partition is ');
CALL osae_sp_object_type_method_add('DSC ALARM PARTITION','DISARM','Disarm','','','','','DSC Alarm Partition is ');

CALL osae_sp_object_type_add ('DSC ALARM ZONE','DSC Alarm Zone','','THING',0,0,0,0,'DSC Alarm Zone');
CALL osae_sp_object_type_state_add ('DSC ALARM ZONE','OPEN','Open','DSC Alarm Zone is ');
CALL osae_sp_object_type_state_add ('DSC ALARM ZONE','CLOSED','Closed','DSC Alarm Zone is ');
CALL osae_sp_object_type_event_add ('DSC ALARM ZONE','CLOSED','Closed','DSC Alarm Zone ');
CALL osae_sp_object_type_event_add ('DSC ALARM ZONE','OPEN','Opened','DSC Alarm Zone ');

CALL osae_sp_object_add ('DSC Alarm','','DSC Alarm','DSC ALARM','3','SYSTEM',30,1,@results);
CALL osae_sp_object_property_set ('Software Version','','DSC Alarm','', null);
CALL osae_sp_object_property_set ('Baud','9600','DSC Alarm','', null);
CALL osae_sp_object_property_set ('Update Time','60','DSC Alarm','', null);
CALL osae_sp_object_property_set ('Code','0','DSC Alarm','', null);
CALL osae_sp_object_property_set ('Password','','DSC Alarm','', null);
CALL osae_sp_object_property_set ('Ethernet','FALSE','DSC Alarm','', null);
CALL osae_sp_object_property_set ('Keybus','','DSC Alarm','', null);

CALL osae_sp_object_add ('Alarm Partition 1','','DSC Alarm Partion 1','DSC ALARM PARTITION','1','SYSTEM',30,1,@results);

CALL osae_sp_object_add ('Alarm Zone 01','','DSC Alarm Zone 1','DSC ALARM ZONE','01','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 02','','DSC Alarm Zone 2','DSC ALARM ZONE','02','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 03','','DSC Alarm Zone 3','DSC ALARM ZONE','03','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 04','','DSC Alarm Zone 4','DSC ALARM ZONE','04','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 05','','DSC Alarm Zone 5','DSC ALARM ZONE','05','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 06','','DSC Alarm Zone 6','DSC ALARM ZONE','06','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 07','','DSC Alarm Zone 7','DSC ALARM ZONE','07','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 08','','DSC Alarm Zone 8','DSC ALARM ZONE','08','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 09','','DSC Alarm Zone 9','DSC ALARM ZONE','09','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 10','','DSC Alarm Zone 10','DSC ALARM ZONE','10','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 11','','DSC Alarm Zone 11','DSC ALARM ZONE','11','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 12','','DSC Alarm Zone 12','DSC ALARM ZONE','12','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 13','','DSC Alarm Zone 13','DSC ALARM ZONE','13','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 14','','DSC Alarm Zone 14','DSC ALARM ZONE','14','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 15','','DSC Alarm Zone 15','DSC ALARM ZONE','15','SYSTEM',30,1,@results);
CALL osae_sp_object_add ('Alarm Zone 16','','DSC Alarm Zone 16','DSC ALARM ZONE','16','SYSTEM',30,1,@results);