//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceAutomation.HostSideAdapters
{
    
    [System.AddIn.Pipeline.HostAdapterAttribute()]
    public class IOpenSourceAutomationAddInContractToViewHostAdapter : OpenSourceAutomation.IOpenSourceAutomationAddInv2
    {
        private OpenSourceAutomation.Contracts.IOpenSourceAutomationAddInContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IOpenSourceAutomationAddInContractToViewHostAdapter()
        {
        }
        public IOpenSourceAutomationAddInContractToViewHostAdapter(OpenSourceAutomation.Contracts.IOpenSourceAutomationAddInContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public void RunInterface(string pluginName)
        {
            _contract.RunInterface(pluginName);
        }
        public void Shutdown()
        {
            _contract.Shutdown();
        }
        public void ProcessCommand(OSAE.OSAEMethod method)
        {
            _contract.ProcessCommand(method);
        }
        internal OpenSourceAutomation.Contracts.IOpenSourceAutomationAddInContract GetSourceContract()
        {
            return _contract;
        }
    }
}

