CALL osae_sp_object_type_add ('RSS','RSS Plugin','','PLUGIN',1,0,0,1,'RSS Plugin');
CALL osae_sp_object_type_state_add ('RSS','ON','Running','RSS Plugin is Running');
CALL osae_sp_object_type_state_add ('RSS','OFF','Stopped','RSS Plugin is Stopped');
CALL osae_sp_object_type_event_add ('RSS','ON','Started','RSS Plugin Started');
CALL osae_sp_object_type_event_add ('RSS','OFF','Stopped','RSS Plugin Stopped');
CALL osae_sp_object_type_method_add ('RSS','ON','Start','','','','','Start the RSS Plugin');
CALL osae_sp_object_type_method_add ('RSS','OFF','Stop','','','','','Stop the RSS Plugin');
CALL osae_sp_object_type_method_add ('RSS','UPDATE','Update','','','','','Update the RSS Plugin');
CALL osae_sp_object_type_property_add ('RSS','Feeds','List','','',0,0,'Feeds');
CALL osae_sp_object_type_property_add ('RSS','Update Interval','String','','60',0,1,'Update Interval');
CALL osae_sp_object_type_property_add('RSS','Version','String','','',0,1,'Version of the RSS plugin');
CALL osae_sp_object_type_property_add('RSS','Author','String','','',0,1,'Author of the RSS plugin');
CALL osae_sp_object_type_property_add('RSS','Trust Level','Integer','','90',0,1,'RSS plugin Trust Level');
