CALL osae_sp_object_type_add ('RSS','RSS Plugin','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('RSS','ON','Running');
CALL osae_sp_object_type_state_add ('RSS','OFF','Stopped');
CALL osae_sp_object_type_event_add ('RSS','ON','Started');
CALL osae_sp_object_type_event_add ('RSS','OFF','Stopped');
CALL osae_sp_object_type_method_add ('RSS','ON','Start','','','','');
CALL osae_sp_object_type_method_add ('RSS','OFF','Stop','','','','');
CALL osae_sp_object_type_method_add ('RSS','UPDATE','Update','','','','');
CALL osae_sp_object_type_property_add ('RSS','Feeds','List','','',0);
CALL osae_sp_object_type_property_add ('RSS','Update Interval','String','','60',0);
CALL osae_sp_object_type_property_add('RSS','Version','String','','',0);
CALL osae_sp_object_type_property_add('RSS','Author','String','','',0);
