//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSAE.PowerShellProcessor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$data = get-osa -name \"Weather\"\n$wc = New-Object System.Net.WebClient\n\n$url = \"ht" +
            "tp://192.168.0.7/emoncms/input/post.json?json={Outside:\" + $data.properties[\"Tem" +
            "p\"].value + \"}&apikey=507ee7ec14130b874b02c241b5740b5e\"\n$wc.UploadString($url, \"" +
            "\")")]
        public string EX1 {
            get {
                return ((string)(this["EX1"]));
            }
        }
    }
}
