CALL osae_sp_object_type_add ('JWORKS','J-Works Plugin','','PLUGIN',1,1,0,1,'J-Works Plugin');
CALL osae_sp_object_type_state_add ('JWORKS','ON','Running','J-Works Plugin is Running');
CALL osae_sp_object_type_state_add ('JWORKS','OFF','Stopped','J-Works Plugin is Stopped');
CALL osae_sp_object_type_event_add ('JWORKS','ON','Started','J-Works Plugin Started');
CALL osae_sp_object_type_event_add ('JWORKS','OFF','Stopped','J-Works Plugin Stopped');
CALL osae_sp_object_type_method_add ('JWORKS','ON','Start','','','','','Start the J-Works Plugin');
CALL osae_sp_object_type_method_add ('JWORKS','OFF','Stop','','','','','Stop the J-Works Plugin');
CALL osae_sp_object_type_method_add ('JWORKS','POLL','Poll Devices now','','','','','Poll Devices now');
CALL osae_sp_object_type_property_add ('JWORKS','Polling Interval','Integer','','',0,1,'Polling Interval');
CALL osae_sp_object_type_property_add('JWORKS','Version','String','','',0,1,'Version of the J-Works plugin');
CALL osae_sp_object_type_property_add('JWORKS','Author','String','','',0,1,'Author of the J-Works plugin');
CALL osae_sp_object_type_property_add('JWORKS','Trust Level','Integer','','90',0,1,'J-Works plugin Trust Level');

CALL osae_sp_object_type_add ('JWORKS INPUT','J-Works Input','','JWORKS INPUT',0,0,0,1,'J-Works Input');
CALL osae_sp_object_type_state_add ('JWORKS INPUT','ON','On','J-Works Input is On');
CALL osae_sp_object_type_state_add ('JWORKS INPUT','OFF','Off','J-Works Input is Off');
CALL osae_sp_object_type_event_add ('JWORKS INPUT','ON','On','J-Works Input turned On');
CALL osae_sp_object_type_event_add ('JWORKS INPUT','OFF','Off','J-Works Input turned Off');
CALL osae_sp_object_type_property_add ('JWORKS INPUT','Serial','String','','',0,0,'Serial');
CALL osae_sp_object_type_property_add ('JWORKS INPUT','Id','String','','',0,0,'Id');
CALL osae_sp_object_type_property_add ('JWORKS INPUT','Invert','Boolean','','FALSE',0,1,'Invert');

CALL osae_sp_object_type_add ('JWORKS OUTPUT','J-Works Output','','JWORKS OUTPUT',0,0,0,1,'J-Works Output');
CALL osae_sp_object_type_state_add ('JWORKS OUTPUT','ON','On','J-Works Output is On');
CALL osae_sp_object_type_state_add ('JWORKS OUTPUT','OFF','Off','J-Works Output is Off');
CALL osae_sp_object_type_event_add ('JWORKS OUTPUT','ON','On','J-Works Output turned On');
CALL osae_sp_object_type_event_add ('JWORKS OUTPUT','OFF','Off','J-Works Output turned On');
CALL osae_sp_object_type_method_add ('JWORKS OUTPUT','ON','On','','','','','Turn On J-Works Output');
CALL osae_sp_object_type_method_add ('JWORKS OUTPUT','OFF','Off','','','','','Turn Off J-Works Output');
CALL osae_sp_object_type_property_add ('JWORKS OUTPUT','Serial','String','','',0,0,'Serial');
CALL osae_sp_object_type_property_add ('JWORKS OUTPUT','Id','String','','',0,0,'Id');
