CALL osae_sp_object_type_delete ('WEATHER');
CALL osae_sp_object_type_add ('WEATHER','Weather Data','','WEATHER',0,1,0,1);
CALL osae_sp_object_type_state_add ('ON','Current','WEATHER');
CALL osae_sp_object_type_state_add ('OFF','Obsolete','WEATHER');
CALL osae_sp_object_type_event_add ('ON','Updated','WEATHER');
CALL osae_sp_object_type_event_add ('OFF','Hung','WEATHER');
CALL osae_sp_object_type_method_add ('ON','Updated','WEATHER','','','','');
CALL osae_sp_object_type_method_add ('OFF','Hung','WEATHER','','','','');
CALL osae_sp_object_type_property_add ('Night1 Low','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Low','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Low','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Low','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 High','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 High','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 High','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 High','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Conditions','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Wind Speed','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Wind Directions','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Humidity','String','','WEATHER',1);
CALL osae_sp_object_type_property_add ('Pressure','String','','WEATHER',1);
CALL osae_sp_object_type_property_add ('Dewpoint','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Visibility','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Windchill','String','','WEATHER',1);
CALL osae_sp_object_type_property_add ('Temp','Integer','','WEATHER',1);
CALL osae_sp_object_type_property_add ('Last Updated','DateTime','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 High','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 High','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Low','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Low','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 High','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Low','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today Precip','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Forecast','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Image','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Summary','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night1 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night2 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night3 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night4 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night5 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night6 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Night7 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day1 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day2 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day3 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day4 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day5 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day6 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Day7 Label','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Sunrise','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Sunset','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Tonight Low','String','','WEATHER',0);
CALL osae_sp_object_type_property_add ('Today High','String','','WEATHER',0);
