CALL osae_sp_object_type_add ('CONTROL MASTER','Control Master Plugin','','PLUGIN',1,1,0,1,'Control Master Plugin');
CALL osae_sp_object_type_state_add('CONTROL MASTER','ON','Running','Control Master Plugin is Running');
CALL osae_sp_object_type_state_add('CONTROL MASTER','OFF','Stopped','Control Master Plugin is Stopped');
CALL osae_sp_object_type_event_add('CONTROL MASTER','ON','Started','Control Master Plugin Started');
CALL osae_sp_object_type_event_add('CONTROL MASTER','OFF','Stopped','Control Master Plugin Stopped');
CALL osae_sp_object_type_method_add('CONTROL MASTER','ON','Start','','','','','Start the Control Master Plugin');
CALL osae_sp_object_type_method_add('CONTROL MASTER','OFF','Stop','','','','','Stop the Control Master Plugin');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Polling Interval','Integer','','',0,0,'Polling Interval');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Attached','Boolean','FALSE','',0,1,'Control Master Attached');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Name','String','','',0,0,'Polling Interval');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Debug','Boolean','FALSE','',0,1,'Add Extra Debug Logging');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Trust Level','Integer','','90',0,1,'Control Master Plugin Trust Level');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Version','String','','',0,0,'Version of the Control Master Plugin');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Author','String','','',0,0,'Author of the Control Master Plugin');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 01 Type','String','','',0,0,'Board 01 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 02 Type','String','','',0,0,'Board 02 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 03 Type','String','','',0,0,'Board 03 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 04 Type','String','','',0,0,'Board 04 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 05 Type','String','','',0,0,'Board 05 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 06 Type','String','','',0,0,'Board 06 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 07 Type','String','','',0,0,'Board 07 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 08 Type','String','','',0,0,'Board 08 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 09 Type','String','','',0,0,'Board 09 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 10 Type','String','','',0,0,'Board 10 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 11 Type','String','','',0,0,'Board 11 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 12 Type','String','','',0,0,'Board 12 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 13 Type','String','','',0,0,'Board 13 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 14 Type','String','','',0,0,'Board 14 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 15 Type','String','','',0,0,'Board 15 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 16 Type','String','','',0,0,'Board 16 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 17 Type','String','','',0,0,'Board 17 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 18 Type','String','','',0,0,'Board 18 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 19 Type','String','','',0,0,'Board 19 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 20 Type','String','','',0,0,'Board 20 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 21 Type','String','','',0,0,'Board 21 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 22 Type','String','','',0,0,'Board 22 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 23 Type','String','','',0,0,'Board 23 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 24 Type','String','','',0,0,'Board 24 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 25 Type','String','','',0,0,'Board 25 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 26 Type','String','','',0,0,'Board 26 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 27 Type','String','','',0,0,'Board 27 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 28 Type','String','','',0,0,'Board 28 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 29 Type','String','','',0,0,'Board 29 Type');
CALL osae_sp_object_type_property_add('CONTROL MASTER','Board 30 Type','String','','',0,0,'Board 30 Type');

CALL osae_sp_object_type_add ('CONTROL MASTER DIGITAL INPUT','Control Master Digital Input','','SENSOR',0,0,0,0,'Control Master Digital Input');
CALL osae_sp_object_type_state_add('CONTROL MASTER DIGITAL INPUT','ON','On','Control Master Digital Input is On');
CALL osae_sp_object_type_state_add('CONTROL MASTER DIGITAL INPUT','OFF','Off','Control Master Digital Input is Off');
CALL osae_sp_object_type_event_add('CONTROL MASTER DIGITAL INPUT','ON','On','Control Master Digital Input On');
CALL osae_sp_object_type_event_add('CONTROL MASTER DIGITAL INPUT','OFF','Off','Control Master Digital Input Off');
CALL osae_sp_object_type_property_add('CONTROL MASTER DIGITAL INPUT','Invert','Boolean','FALSE','',0,1,'Control Master Digital Input Off Timer');

CALL osae_sp_object_type_add ('CONTROL MASTER DIGITAL OUTPUT','Control Master Digital Output','','SWITCH',0,0,0,0,'Control Master Digital Output');
CALL osae_sp_object_type_state_add('CONTROL MASTER DIGITAL OUTPUT','ON','On','Control Master Digital Output is On');
CALL osae_sp_object_type_state_add('CONTROL MASTER DIGITAL OUTPUT','OFF','Off','Control Master Digital Output is Off');
CALL osae_sp_object_type_event_add('CONTROL MASTER DIGITAL OUTPUT','ON','On','Control Master Digital Output On');
CALL osae_sp_object_type_event_add('CONTROL MASTER DIGITAL OUTPUT','OFF','Off','Control Master Digital Output Off');
CALL osae_sp_object_type_method_add('CONTROL MASTER DIGITAL OUTPUT','ON','On','','','','','Turn the Control Master Digital Output On');
CALL osae_sp_object_type_method_add('CONTROL MASTER DIGITAL OUTPUT','OFF','Off','','','','','Turn the Control Master Digital Output Off');
CALL osae_sp_object_type_property_add('CONTROL MASTER DIGITAL OUTPUT','Off Timer','Integer','-1','',0,1,'Control Master Digital Output Off Timer');