CALL osae_sp_object_type_add ('ONKYO','Onkyo Plugin','','PLUGIN',1,1,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','ONKYO');
CALL osae_sp_object_type_state_add ('OFF','Stopped','ONKYO');
CALL osae_sp_object_type_event_add ('ON','Started','ONKYO');
CALL osae_sp_object_type_event_add ('OFF','Stopped','ONKYO');
CALL osae_sp_object_type_method_add ('ON','Start','ONKYO','','','','');
CALL osae_sp_object_type_method_add ('OFF','Stop','ONKYO','','','','');
CALL osae_sp_object_type_method_add ('SCAN','Scan for Receivers','ONKYO','','','','');
CALL osae_sp_object_type_property_add ('System Plugin','String','TRUE','ONKYO',0);

CALL osae_sp_object_type_add ('ONKYO RECEIVER','Onkyo Receiver','','ONKYO RECEIVER',0,0,0,1);
CALL osae_sp_object_type_state_add ('ON','On','ONKYO RECEIVER');
CALL osae_sp_object_type_state_add ('OFF','Off','ONKYO RECEIVER');
CALL osae_sp_object_type_event_add ('ON','On','ONKYO RECEIVER');
CALL osae_sp_object_type_event_add ('OFF','Off','ONKYO RECEIVER');
CALL osae_sp_object_type_method_add ('ON','On','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('OFF','Standby','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('MUTE', 'Mute', 'ONKYO RECEIVER', '', '', '', '');
CALL osae_sp_object_type_method_add ('UNMUTE', 'Un-Mute', 'ONKYO RECEIVER', '', '', '', '');
CALL osae_sp_object_type_method_add ('VOLUME UP', 'Turn Volume Up', 'ONKYO RECEIVER', '', '', '', '');
CALL osae_sp_object_type_method_add ('VOLUME DOWN', 'Turn Volume Down', 'ONKYO RECEIVER', '', '', '', '');
CALL osae_sp_object_type_method_add ('SET VOLUME', 'Set Volume', 'ONKYO RECEIVER', 'Level', '', '', '');
CALL osae_sp_object_type_method_add ('VCR/DVR','VCR/DVR','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('CBL/SAT','CBL/SAT','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('GAME','Game','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('AUX1','Aux1','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('BD/DVD','BD/DVD','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('TUNER','Tuner','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('TV/CD','TV/CD','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('DLNA','Net-DLNA','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('VTUNER','Net-vTuner','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('PANDORA','Net-Pandora','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('SIRIUS','Net-SiriusXM','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('MEDIAFLY','Net-Mediafly','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('NAPSTER','Net-Napster','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('FAVORITES','Net-My Favorites','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('UP','Up','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('DOWN','Down','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('LEFT','Left','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('RIGHT','Right','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('ENTER','Enter','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('NETUP','Net-Up','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('NETDOWN','Net-Down','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('NETLEFT','Net-Left','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('NETRIGHT','Net-Right','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_method_add ('NETENTER','Net-Enter','ONKYO RECEIVER','','','','');
CALL osae_sp_object_type_property_add ('Communication Type','String','','ONKYO RECEIVER',0);
CALL osae_sp_object_type_property_add ('Network Port','String','','ONKYO RECEIVER',0);
CALL osae_sp_object_type_property_add ('IP','Integer','','ONKYO RECEIVER',0);
CALL osae_sp_object_type_property_add ('COM Port','Integer','','ONKYO RECEIVER',0);
CALL osae_sp_object_type_property_option_add('ONKYO RECEIVER','Communication Type','Network');
CALL osae_sp_object_type_property_option_add('ONKYO RECEIVER','Communication Type','Serial');