CALL osae_sp_object_type_add ('CM15A','X10 Plugin Class','','PLUGIN',1,0,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','CM15A');
CALL osae_sp_object_type_state_add ('OFF','Stopped','CM15A');
CALL osae_sp_object_type_event_add ('ON','Started','CM15A');
CALL osae_sp_object_type_event_add ('OFF','Stopped','CM15A');
CALL osae_sp_object_type_method_add ('ON','Start','CM15A','','','','');
CALL osae_sp_object_type_method_add ('OFF','Stop','CM15A','','','','');
CALL osae_sp_object_type_method_add ('DEBOUNCE','Set Debounce Time','CM15A','Time in ms','','120','');
CALL osae_sp_object_type_method_add ('DEBUG MODE','Set Debug Mode','CM15A','TRUE/FALSE','','FALSE','');
CALL osae_sp_object_type_method_add ('TRANSMIT ONLY','Set Transmit Only','CM15A','TRUE / FALSE','','FALSE','');
CALL osae_sp_object_type_method_add ('TRANSMIT RF','Set Transmit RF','CM15A','TRUE / FALSE','','FALSE','');
CALL osae_sp_object_type_method_add ('ALLLIGHTSON','All Lights On','CM15A','HouseCode','','A1','');
CALL osae_sp_object_type_method_add ('ALLLIGHTSOFF','All Lights Off','CM15A','HouseCode','','A1','');
CALL osae_sp_object_type_property_add ('Computer Name','Integer','','CM15A',0);
CALL osae_sp_object_type_property_add ('Transmit Only','Boolean','FALSE','CM15A',0);
CALL osae_sp_object_type_property_add ('Transmit RF','Boolean','FALSE','CM15A',0);
CALL osae_sp_object_type_property_add ('Debounce','Integer','120','CM15A',0);
CALL osae_sp_object_type_property_add ('System Plugin','Boolean','FALSE','CM15A',0);

CALL osae_sp_object_type_add ('X10 DIMMER','X10 Dimmer','','X10 DIMMER',1,1,0,0);
CALL osae_sp_object_type_state_add ('ON','On','X10 DIMMER');
CALL osae_sp_object_type_state_add ('OFF','Off','X10 DIMMER');
CALL osae_sp_object_type_event_add ('ON','On','X10 DIMMER');
CALL osae_sp_object_type_event_add ('OFF','Off','X10 DIMMER');
CALL osae_sp_object_type_method_add ('ON','On','X10 DIMMER','Dim Level in %','','100','');
CALL osae_sp_object_type_method_add ('OFF','Off','X10 DIMMER','','','','');
CALL osae_sp_object_type_method_add ('BRIGHT','Bright','X10 DIMMER','Increment %','','10','');
CALL osae_sp_object_type_method_add ('DIM','Dim','X10 DIMMER','Decrement %','','10','');
CALL osae_sp_object_type_property_add ('Off Timer','Integer','','X10 DIMMER',0);
CALL osae_sp_object_type_property_add ('Level','Integer','','X10 DIMMER',1);
CALL osae_sp_object_type_property_add ('SoftStart','Boolean','FALSE','X10 DIMMER',0);