CALL osae_sp_object_type_add ('CM15A','X10 Plugin Class','CM15A','PLUGIN',1,0,0,1,'X-10 CM15a/CM19a plugin.');
CALL osae_sp_object_type_state_add('CM15A','ON','Running','The CM15A plugin is Running');
CALL osae_sp_object_type_state_add('CM15A','OFF','Stopped','The CM15A plugin is Stopped');
CALL osae_sp_object_type_event_add('CM15A','ON','Started','The CM15A plugin Started.');
CALL osae_sp_object_type_event_add('CM15A','OFF','Stopped','The CM15A plugin Stopped.');
CALL osae_sp_object_type_method_add('CM15A','ON','Start','','','','','Start the CM15A plugin.');
CALL osae_sp_object_type_method_add('CM15A','OFF','Stop','','','','','Stop the CM15A plugin.');
CALL osae_sp_object_type_method_add('CM15A','DEBOUNCE','Set Debounce Time','Time in ms','','120','','Set the Debounce time.');
CALL osae_sp_object_type_method_add('CM15A','DEBUG MODE','Set Debug Mode','TRUE/FALSE','','FALSE','','Set the plugin Debug Mode.');
CALL osae_sp_object_type_method_add('CM15A','TRANSMIT ONLY','Set Transmit Only','TRUE / FALSE','','FALSE','','Set Transmit Only property.');
CALL osae_sp_object_type_method_add('CM15A','TRANSMIT RF','Set Transmit RF','TRUE / FALSE','','FALSE','','Set the Transmit RF property.');
CALL osae_sp_object_type_property_add('CM15A','Transmit Only','Boolean','','FALSE',0,1,'Select True/False to Transmit data only.');
CALL osae_sp_object_type_property_add('CM15A','Transmit RF','Boolean','','FALSE',0,1,'Select True/False to Transmit RF at all.');
CALL osae_sp_object_type_property_add('CM15A','Debounce','Integer','','120',0,1,'Enter the Debounce time in seconds.');
CALL osae_sp_object_type_property_add('CM15A','System Plugin','Boolean','','FALSE',0,0,'This designates if this is a system plugin.');
CALL osae_sp_object_type_property_add('CM15A','Trust Level','Integer','','50',0,1,'The Trust Level of the CM15A plugin.');
CALL osae_sp_object_type_property_add('CM15A','Version','String','','',0,0,'This is the Version of the CM15A Plugin.');
CALL osae_sp_object_type_property_add('CM15A','Author','String','','',0,0,'This is the Author of the CM15A Plugin.');

CALL osae_sp_object_type_add ('X10 DIMMER','X10 Dimmer','','SWITCH',0,0,0,0,'X10 Dimmer');
CALL osae_sp_object_type_state_add('X10 DIMMER','ON','On','On');
CALL osae_sp_object_type_state_add('X10 DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 DIMMER','ON','On','On');
CALL osae_sp_object_type_event_add('X10 DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_method_add('X10 DIMMER','ON','On','Dim Level in %','','100','','Turn On');
CALL osae_sp_object_type_method_add('X10 DIMMER','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_method_add('X10 DIMMER','BRIGHT','Bright','Increment %','','10','','Bright');
CALL osae_sp_object_type_method_add('X10 DIMMER','DIM','Dim','Decrement %','','10','','Dim');
CALL osae_sp_object_type_property_add('X10 DIMMER','Off Timer','Integer','','-1',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('X10 DIMMER','Level','Integer','','0',0,0,'Dim Level 0-100%');
CALL osae_sp_object_type_property_add('X10 DIMMER','Soft Start','Boolean','','FALSE',0,0,'Soft Start');

CALL osae_sp_object_type_add ('X10 RELAY','X10 Relay','','SWITCH',0,0,0,0,'X10 Relay');
CALL osae_sp_object_type_state_add('X10 RELAY','ON','On','On');
CALL osae_sp_object_type_state_add('X10 RELAY','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 RELAY','ON','On','On');
CALL osae_sp_object_type_event_add('X10 RELAY','OFF','Off','Off');
CALL osae_sp_object_type_method_add('X10 RELAY','ON','On','','','','','Turn On');
CALL osae_sp_object_type_method_add('X10 RELAY','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_property_add('X10 RELAY','Off Timer','Integer','','-1',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('X10 RELAY','Soft Start','Boolean','','FALSE',0,0,'Soft Start');

CALL osae_sp_object_type_add ('X10 SENSOR','X10 Sensor','','SENSOR',0,0,0,0,'X10 Sensor');
CALL osae_sp_object_type_state_add('X10 SENSOR','ON','On','On');
CALL osae_sp_object_type_state_add('X10 SENSOR','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 SENSOR','ON','On','On');
CALL osae_sp_object_type_event_add('X10 SENSOR','OFF','Off','Off');
CALL osae_sp_object_type_property_add('X10 SENSOR','Off Timer','Integer','','-1',0,1,'Off Timer');
CALL osae_sp_object_type_property_add('X10 SENSOR','Level','Integer','','0',0,0,'Level');

CALL osae_sp_object_type_add ('X10 PHOTOCELL','X10 Photocell','','SENSOR',0,0,0,0,'X10 Photocell');
CALL osae_sp_object_type_state_add('X10 PHOTOCELL','ON','Dark','Dark');
CALL osae_sp_object_type_state_add('X10 PHOTOCELL','OFF','Light','Light');
CALL osae_sp_object_type_event_add('X10 PHOTOCELL','ON','Dark','Dark');
CALL osae_sp_object_type_event_add('X10 PHOTOCELL','OFF','Light','Light');
CALL osae_sp_object_type_property_add('X10 PHOTOCELL','Off Timer','Integer','','-1',0,1,'Off Timer');
CALL osae_sp_object_type_property_add('X10 PHOTOCELL','Level','Integer','','0',1,'Level');