//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceAutomation.AddInSideAdapters
{
    
    public class IOpenSourceAutomationAddInAddInAdapter
    {
        internal static OpenSourceAutomation.IOpenSourceAutomationAddInv2 ContractToViewAdapter(OpenSourceAutomation.Contracts.IOpenSourceAutomationAddInContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IOpenSourceAutomationAddInViewToContractAddInAdapter))))
            {
                return ((IOpenSourceAutomationAddInViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IOpenSourceAutomationAddInContractToViewAddInAdapter(contract);
            }
        }
        internal static OpenSourceAutomation.Contracts.IOpenSourceAutomationAddInContract ViewToContractAdapter(OpenSourceAutomation.IOpenSourceAutomationAddInv2 view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IOpenSourceAutomationAddInContractToViewAddInAdapter)))
            {
                return ((IOpenSourceAutomationAddInContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IOpenSourceAutomationAddInViewToContractAddInAdapter(view);
            }
        }
    }
}

