//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenSourceAutomation.AddInSideAdapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class IOpenSourceAutomationAddInViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, OpenSourceAutomation.Contracts.IOpenSourceAutomationAddInContract
    {
        private OpenSourceAutomation.IOpenSourceAutomationAddInv2 _view;
        public IOpenSourceAutomationAddInViewToContractAddInAdapter(OpenSourceAutomation.IOpenSourceAutomationAddInv2 view)
        {
            _view = view;
        }
        public virtual void RunInterface(string pluginName)
        {
            _view.RunInterface(pluginName);
        }
        public virtual void Shutdown()
        {
            _view.Shutdown();
        }
        public virtual void ProcessCommand(OSAE.OSAEMethod method)
        {
            _view.ProcessCommand(method);
        }
        internal OpenSourceAutomation.IOpenSourceAutomationAddInv2 GetSourceView()
        {
            return _view;
        }
    }
}

