-- ***** Object type for the TELLSTICK plugin *****
CALL osae_sp_object_type_add ('TELLSTICK','TELLSTICK Plugin','Tellstick','PLUGIN',1,1,0,1,'TELLSTICK Plugin');
CALL osae_sp_object_type_state_add('TELLSTICK','OFF','Stopped','TELLSTICK Plugin');
CALL osae_sp_object_type_state_add('TELLSTICK','ON','Running','TELLSTICK Plugin');
CALL osae_sp_object_type_event_add('TELLSTICK','OFF','Stopped','TELLSTICK Plugin');
CALL osae_sp_object_type_event_add('TELLSTICK','ON','Started','TELLSTICK Plugin');
CALL osae_sp_object_type_method_add('TELLSTICK','OFF','Stop','','','','','TELLSTICK Plugin');
CALL osae_sp_object_type_method_add('TELLSTICK','ON','Start','','','','','TELLSTICK Plugin');
CALL osae_sp_object_type_method_add('TELLSTICK','DEBUGON','Debug ON','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK','DEBUGOFF','Debug OFF','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK','REINIT','Re-initialise','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK','RESTORE','Restore object types','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK','NoOfDevices','Integer',0,'',0);
CALL osae_sp_object_type_property_add('TELLSTICK','AddressPrefix','String',0,'TellstickId-',0);
CALL osae_sp_object_type_property_add('TELLSTICK','AddressPrefixSensor','String',0,'TellstickSensor-',0);
CALL osae_sp_object_type_property_add('TELLSTICK','RawEvents','Boolean',0,'FALSE',0);
CALL osae_sp_object_type_property_add('TELLSTICK','AddDevices','Boolean',0,'TRUE',0);
CALL osae_sp_object_type_property_add('TELLSTICK','AddSensors','Boolean',0,'TRUE',0);
CALL osae_sp_object_type_property_add('TELLSTICK','Computer Name','String',0,'',0);
CALL osae_sp_object_type_property_add('TELLSTICK','Port','String',0,'USB',0);
CALL osae_sp_object_type_property_add('TELLSTICK','System Plugin','Boolean',0,'FALSE',0);
CALL osae_sp_object_type_property_add('TELLSTICK','Debug','Boolean',0,'FALSE',1);
CALL osae_sp_object_type_property_add('TELLSTICK','AverageInt','Integer',0,'10',0);
CALL osae_sp_object_type_property_add('TELLSTICK','Trust Level','Integer','','90',0);
CALL osae_sp_object_type_property_add('TELLSTICK','Version','String','','',0);
CALL osae_sp_object_type_property_add('TELLSTICK','Author','String','','',0);

-- ***** Tellstick object
CALL osae_sp_object_add ('Tellstick','Tellstick','TELLSTICK Plugin','TELLSTICK','','SYSTEM','50',1,@results);
CALL osae_sp_object_property_set('Tellstick','NoOfDevices','0','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','AddressPrefix','TellstickId-','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','AddressPrefixSensor','TellstickSensor-','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','RawEvents','FALSE','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','AddDevices','TRUE','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','AddSensors','TRUE','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','Computer Name','','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','Port','USB','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','System Plugin','FALSE','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','Debug','FALSE','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','AverageInt','10','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','Trust Level','90','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','Version','0.4.8','SYSTEM','Import');
CALL osae_sp_object_property_set('Tellstick','Author','Per Tobiasson','SYSTEM','Import');

-- ***** Base Object types needed by Tellstick
CALL osae_sp_object_type_add ('BINARY SWITCH','Binary Switch','','BINARY SWITCH',0,1,0,1);
CALL osae_sp_object_type_state_add('BINARY SWITCH','ON','On');
CALL osae_sp_object_type_state_add('BINARY SWITCH','OFF','Off');
CALL osae_sp_object_type_event_add('BINARY SWITCH','ON','On');
CALL osae_sp_object_type_event_add('BINARY SWITCH','OFF','Off');
CALL osae_sp_object_type_method_add('BINARY SWITCH','ON','On','','','','');
CALL osae_sp_object_type_method_add('BINARY SWITCH','OFF','Off','','','','');

CALL osae_sp_object_type_add ('HUMIDITY METER','Humidity Meter','','HUMIDITY METER',0,0,0,1);
CALL osae_sp_object_type_event_add('HUMIDITY METER','HUMIDITY','Humidity Changed');
CALL osae_sp_object_type_property_add('HUMIDITY METER','Humidity','String',0,'',0);
CALL osae_sp_object_type_property_add('HUMIDITY METER','Status','String',0,'',0);
CALL osae_sp_object_type_property_add('HUMIDITY METER','Battery','String',0,'',0);

CALL osae_sp_object_type_add ('MULTILEVEL SWITCH','Multilevel Switch','','MULTILEVEL SWITCH',0,1,0,1);
CALL osae_sp_object_type_state_add('MULTILEVEL SWITCH','ON','On');
CALL osae_sp_object_type_state_add('MULTILEVEL SWITCH','OFF','Off');
CALL osae_sp_object_type_event_add('MULTILEVEL SWITCH','ON','On');
CALL osae_sp_object_type_event_add('MULTILEVEL SWITCH','OFF','Off');
CALL osae_sp_object_type_method_add('MULTILEVEL SWITCH','ON','On','Level','100','','');
CALL osae_sp_object_type_method_add('MULTILEVEL SWITCH','OFF','Off','','','','');
CALL osae_sp_object_type_property_add('MULTILEVEL SWITCH','Level','String',0,'',0);

CALL osae_sp_object_type_add ('TEMP HUM METER','Temperature and Humidity Meter','','TEMP HUM METER',0,0,0,1);
CALL osae_sp_object_type_event_add('TEMP HUM METER','HUMIDITY','Humidity Changed');
CALL osae_sp_object_type_property_add('TEMP HUM METER','Temperature','String',0,'',0);
CALL osae_sp_object_type_property_add('TEMP HUM METER','Humidity','String',0,'',0);
CALL osae_sp_object_type_property_add('TEMP HUM METER','Status','String',0,'',0);
CALL osae_sp_object_type_property_add('TEMP HUM METER','Battery','String',0,'',0);

CALL osae_sp_object_type_add ('TEMPERATURE SENSOR','Temperature sensor','','TEMPERATURE SENSOR',0,1,0,1);
CALL osae_sp_object_type_state_add('TEMPERATURE SENSOR','ON','On');
CALL osae_sp_object_type_state_add('TEMPERATURE SENSOR','OFF','Off');
CALL osae_sp_object_type_property_add('TEMPERATURE SENSOR','Temperature','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TEMPERATURE SENSOR','Unit','String',0,'C',1);

CALL osae_sp_object_type_add ('UP-DOWN DEVICE','UP-DOWN Device','','UP-DOWN DEVICE',0,1,0,1);
CALL osae_sp_object_type_state_add('UP-DOWN DEVICE','ON','On');
CALL osae_sp_object_type_state_add('UP-DOWN DEVICE','OFF','Off');
CALL osae_sp_object_type_event_add('UP-DOWN DEVICE','UP','Up');
CALL osae_sp_object_type_event_add('UP-DOWN DEVICE','DOWN','Down');
CALL osae_sp_object_type_event_add('UP-DOWN DEVICE','STOP','Stop');
CALL osae_sp_object_type_method_add('UP-DOWN DEVICE','UP','Up','','','','');
CALL osae_sp_object_type_method_add('UP-DOWN DEVICE','DOWN','Down','','','','');
CALL osae_sp_object_type_method_add('UP-DOWN DEVICE','STOP','Stop','','','','');

-- ***** Containers to place Tellstic objects in *****
CALL osae_sp_object_add ('SENSORS','SENSORS','Container for sensors','CONTAINER','','Unknown','50',1,@results);
CALL osae_sp_object_add ('SWITCHES','SWITCHES','Container for SWITCHES','CONTAINER','','Unknown','50',1,@results);

-- ***** Object types for different Tellstick devices *****
CALL osae_sp_object_type_add ('TELLSTICK BELL','BELL Device on Tellstick Plugin','Tellstick','TELLSTICK BELL',0,0,0,0);
CALL osae_sp_object_type_state_add('TELLSTICK BELL','OFF','Off');
CALL osae_sp_object_type_state_add('TELLSTICK BELL','ON','On');
CALL osae_sp_object_type_state_add('TELLSTICK BELL','DISABLE','Disabled');
CALL osae_sp_object_type_state_add('TELLSTICK BELL','UNKNOWN','Unknown');
CALL osae_sp_object_type_event_add('TELLSTICK BELL','BELL','Bell');
CALL osae_sp_object_type_method_add('TELLSTICK BELL','DISABLE','Disable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BELL','ENABLE','Enable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BELL','BELL','Bell','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BELL','LEARN','Learn','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BELL','DEBUGOFF','Debug OFF','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BELL','DEBUGON','Debug ON','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BELL','RESTORE','Restore Object type','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK BELL','DeviceId','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','Model','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','Protocol','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','LastSentCommand','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','Level','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','DeviceType','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','Methods','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','DeviceAddress','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','DeviceChangeEvents','Boolean',0,'TRUE',1);
CALL osae_sp_object_type_property_add('TELLSTICK BELL','Debug','Boolean',0,'TRUE',0);

-- CALL osae_sp_object_type_add ('TELLSTICK BELL (LEARN)','BELL Device on Tellstick Plugin','Tellstick','TELLSTICK BELL (LEARN)',0,0,0,0);
-- CALL osae_sp_object_type_state_add('TELLSTICK BELL (LEARN)','OFF','Off');
-- CALL osae_sp_object_type_state_add('TELLSTICK BELL (LEARN)','ON','On');
-- CALL osae_sp_object_type_state_add('TELLSTICK BELL (LEARN)','DISABLE','Disabled');
-- CALL osae_sp_object_type_state_add('TELLSTICK BELL (LEARN)','UNKNOWN','Unknown');
-- CALL osae_sp_object_type_event_add('TELLSTICK BELL (LEARN)','BELL','Bell');
-- CALL osae_sp_object_type_event_add('TELLSTICK BELL (LEARN)','LEARN','Learn');
-- CALL osae_sp_object_type_method_add('TELLSTICK BELL (LEARN)','DISABLE','Disable','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BELL (LEARN)','ENABLE','Enable','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BELL (LEARN)','BELL','Bell','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BELL (LEARN)','LEARN','Learn','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BELL (LEARN)','DEBUGON','Debug ON','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BELL (LEARN)','DEBUGOFF','Debug OFF','','','','');
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','DeviceId','Integer',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','Model','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','Protocol','Integer',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','LastSentCommand','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','Level','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','DeviceType','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','Methods','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','DeviceAddress','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','DeviceChangeEvents','Boolean',0,'TRUE',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BELL (LEARN)','Debug','Boolean',0,'TRUE',0);

CALL osae_sp_object_type_add ('TELLSTICK BINARY SWITCH','ON-OFF Device on Tellstick Plugin','Tellstick','BINARY SWITCH',0,0,0,1);
CALL osae_sp_object_type_state_add('TELLSTICK BINARY SWITCH','OFF','Off');
CALL osae_sp_object_type_state_add('TELLSTICK BINARY SWITCH','ON','On');
CALL osae_sp_object_type_state_add('TELLSTICK BINARY SWITCH','DISABLE','Disabled');
CALL osae_sp_object_type_state_add('TELLSTICK BINARY SWITCH','UNKNOWN','Unknown');
CALL osae_sp_object_type_event_add('TELLSTICK BINARY SWITCH','OFF','Off');
CALL osae_sp_object_type_event_add('TELLSTICK BINARY SWITCH','ON','On');
CALL osae_sp_object_type_event_add('TELLSTICK BINARY SWITCH','TOGGLE','Toggle');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','OFF','Off','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','ON','On','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','TOGGLE','Toggle','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','DISABLE','Disable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','ENABLE','Enable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','LEARN','Learn','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','DEBUGON','Debug ON','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','DEBUGOFF','Debug OFF','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH','RESTORE','Restore Object type','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','DeviceId','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','Model','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','Protocol','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','LastSentCommand','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','Level','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','DeviceType','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','Methods','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','DeviceAddress','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','DeviceChangeEvents','Boolean',0,'TRUE',1);
CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH','Debug','Boolean',0,'TRUE',0);

-- CALL osae_sp_object_type_add ('TELLSTICK BINARY SWITCH (LEARN)','ON-OFF Device on Tellstick Plugin','Tellstick','BINARY SWITCH',0,0,0,1);
-- CALL osae_sp_object_type_state_add('TELLSTICK BINARY SWITCH (LEARN)','OFF','Off');
-- CALL osae_sp_object_type_state_add('TELLSTICK BINARY SWITCH (LEARN)','ON','On');
-- CALL osae_sp_object_type_state_add('TELLSTICK BINARY SWITCH (LEARN)','DISABLE','Disabled');
-- CALL osae_sp_object_type_state_add('TELLSTICK BINARY SWITCH (LEARN)','UNKNOWN','Unknown');
-- CALL osae_sp_object_type_event_add('TELLSTICK BINARY SWITCH (LEARN)','OFF','Off');
-- CALL osae_sp_object_type_event_add('TELLSTICK BINARY SWITCH (LEARN)','ON','On');
-- CALL osae_sp_object_type_event_add('TELLSTICK BINARY SWITCH (LEARN)','TOGGLE','Toggle');
-- CALL osae_sp_object_type_event_add('TELLSTICK BINARY SWITCH (LEARN)','LEARN','Learn');
-- CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH (LEARN)','OFF','Off','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH (LEARN)','ON','On','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH (LEARN)','TOGGLE','Toggle','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH (LEARN)','LEARN','Learn','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH (LEARN)','DISABLE','Disable','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH (LEARN)','ENABLE','Enable','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH (LEARN)','DEBUGOFF','Debug OFF','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK BINARY SWITCH (LEARN)','DEBUGON','Debug ON','','','','');
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','DeviceId','Integer',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','Model','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','Protocol','Integer',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','LastSentCommand','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','Level','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','DeviceType','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','Methods','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','DeviceAddress','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','DeviceChangeEvents','Boolean',0,'TRUE',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK BINARY SWITCH (LEARN)','Debug','Boolean',0,'TRUE',0);

-- CALL osae_sp_object_type_add ('TELLSTICK DEVICE','Device on Tellstick Plugin','TELLSTICK','SYSTEM',1,1,0,1);
-- CALL osae_sp_object_type_state_add ('TELLSTICK DEVICE','OFF','Off');
-- CALL osae_sp_object_type_state_add ('TELLSTICK DEVICE','ON','On');
-- CALL osae_sp_object_type_state_add ('TELLSTICK DEVICE','DISABLE','Disabled');
-- CALL osae_sp_object_type_state_add ('TELLSTICK DEVICE','UNKNOWN','Unknown');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','OFF','Off');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','ON','On');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','STOP','Stop');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','TOGGLE','Toggle');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','DIM','Dim');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','UP','Up');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','DOWN','Down');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','EXECUTE','Execute');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','LEARN','Learn');
-- CALL osae_sp_object_type_event_add ('TELLSTICK DEVICE','BELL','Bell');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','OFF','Off','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','ON','On','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','UP','Up','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','DOWN','Down','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','STOP','Stop','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','TOGGLE','Toggle','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','EXECUTE','Execute','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','DIM','Dim','Level','','100','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','LEARN','Learn','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','BELL','Bell','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','DISABLE','Disable','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','ENABLE','Enable','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','DEBUGON','SetDebug','','','','');
-- CALL osae_sp_object_type_method_add ('TELLSTICK DEVICE','DEBUGOFF','SetDebug','','','','');
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','DeviceId','Integer',0,'',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','Model','String',0,'',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','Protocol','Integer',0,'',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','LastSentCommand','String',0,'',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','Level','String',0,'',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','DeviceType','String',0,'',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','Methods','String',0,'',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','DeviceAddress','String',0,'',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','DeviceChangeEvents','Boolean',0,'TRUE',0);
-- CALL osae_sp_object_type_property_add ('TELLSTICK DEVICE','Debug','Boolean',0,'TRUE',0);

CALL osae_sp_object_type_add('TELLSTICK GROUP DEVICE','Device on Tellstick Plugin','Tellstick','TELLSTICK',0,0,0,1);
CALL osae_sp_object_type_state_add('TELLSTICK GROUP DEVICE','OFF','Off');
CALL osae_sp_object_type_state_add('TELLSTICK GROUP DEVICE','ON','On');
CALL osae_sp_object_type_state_add('TELLSTICK GROUP DEVICE','DISABLE','Disabled');
CALL osae_sp_object_type_state_add('TELLSTICK GROUP DEVICE','UNKNOWN','Unknown');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','OFF','Off');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','ON','On');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','STOP','Stop');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','TOGGLE','Toggle');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','DIM','Dim');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','UP','Up');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','DOWN','Down');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','EXECUTE','Execute');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','LEARN','Learn');
CALL osae_sp_object_type_event_add('TELLSTICK GROUP DEVICE','BELL','Bell');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','OFF','Off','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','ON','On','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','UP','Up','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','DOWN','Down','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','STOP','Stop','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','TOGGLE','Toggle','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','EXECUTE','Execute','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','DIM','Dim','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','LEARN','Learn','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','BELL','Bell','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','DISABLE','Disable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','ENABLE','Enable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK GROUP DEVICE','RESTORE','Restore Object type','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','DeviceId','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','Model','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','Protocol','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','LastSentCommand','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','Level','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','DeviceType','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','Methods','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','DeviceAddress','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK GROUP DEVICE','DeviceChangeEvents','Boolean',0,'TRUE',1);

CALL osae_sp_object_type_add ('TELLSTICK HUMIDITY SENSOR','Humidity sensor','Tellstick','HUMIDITY METER',0,0,0,1);
CALL osae_sp_object_type_state_add('TELLSTICK HUMIDITY SENSOR','ON','On');
CALL osae_sp_object_type_state_add('TELLSTICK HUMIDITY SENSOR','OFF','Off');
CALL osae_sp_object_type_state_add('TELLSTICK HUMIDITY SENSOR','DISABLE','Disabled');
CALL osae_sp_object_type_state_add('TELLSTICK HUMIDITY SENSOR','UNKNOWN','Unknown');
CALL osae_sp_object_type_event_add('TELLSTICK HUMIDITY SENSOR','HUMIDITY','Humidity');
CALL osae_sp_object_type_event_add('TELLSTICK HUMIDITY SENSOR','AVERAGEHUM','AverageHum');
CALL osae_sp_object_type_event_add('TELLSTICK HUMIDITY SENSOR','MAXHUM','MaxHum');
CALL osae_sp_object_type_event_add('TELLSTICK HUMIDITY SENSOR','MINHUM','MinHum');
CALL osae_sp_object_type_method_add('TELLSTICK HUMIDITY SENSOR','ENABLE','Enable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK HUMIDITY SENSOR','DISABLE','Disable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK HUMIDITY SENSOR','DEBUGON','Debug ON','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK HUMIDITY SENSOR','DEBUGOFF','Debug OFF','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK HUMIDITY SENSOR','RESETMAXMIN','Reset Max-Min','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK HUMIDITY SENSOR','RESTORE','Restore Object type','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','Humidity','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','DeviceAddress','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','DeviceId','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','DeviceType','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','Model','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','Protocol','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','OFF TIMER','Integer',0,'600',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','Status','String',0,'Not Implemented',0);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','Battery','String',0,'Not Implemented',0);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','Debug','Boolean',0,'TRUE',0);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','AverageHum','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','MaxHum','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK HUMIDITY SENSOR','MinHum','Float',0,'100',1);

CALL osae_sp_object_type_add ('TELLSTICK MULTILEVEL SWITCH','DIM Device on Tellstick Plugin','Tellstick','MULTILEVEL SWITCH',0,0,0,1);
CALL osae_sp_object_type_state_add('TELLSTICK MULTILEVEL SWITCH','OFF','Off');
CALL osae_sp_object_type_state_add('TELLSTICK MULTILEVEL SWITCH','ON','On');
CALL osae_sp_object_type_state_add('TELLSTICK MULTILEVEL SWITCH','DISABLE','Disabled');
CALL osae_sp_object_type_state_add('TELLSTICK MULTILEVEL SWITCH','UNKNOWN','Unknown');
CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH','OFF','Off');
CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH','ON','On');
CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH','TOGGLE','Toggle');
CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH','DIM','Dim');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','OFF','Off','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','ON','On','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','TOGGLE','Toggle','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','DIM','Dim','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','DISABLE','Disable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','ENABLE','Enable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','LEARN','Learn','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','DEBUGOFF','Debug OFF','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','DEBUGON','Debug ON','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH','RESTORE','Restore Object type','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','DeviceId','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','Model','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','Protocol','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','LastSentCommand','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','Level','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','DeviceType','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','Methods','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','DeviceAddress','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','DeviceChangeEvents','Boolean',0,'TRUE',1);
CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH','Debug','Boolean',0,'TRUE',0);

-- CALL osae_sp_object_type_add ('TELLSTICK MULTILEVEL SWITCH (LEARN)','DIM Device on Tellstick Plugin','Tellstick','MULTILEVEL SWITCH',0,0,0,1);
-- CALL osae_sp_object_type_state_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','OFF','Off');
-- CALL osae_sp_object_type_state_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','ON','On');
-- CALL osae_sp_object_type_state_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DISABLE','Disabled');
-- CALL osae_sp_object_type_state_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','UNKNOWN','Unknown');
-- CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','OFF','Off');
-- CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','ON','On');
-- CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','TOGGLE','Toggle');
-- CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DIM','Dim');
-- CALL osae_sp_object_type_event_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','LEARN','Learn');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','OFF','Off','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','ON','On','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','TOGGLE','Toggle','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DIM','Dim','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','LEARN','Learn','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DISABLE','Disable','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','ENABLE','Enable','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DEBUGON','Debug ON','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DEBUGOFF','Debug OFF','','','','');
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DeviceId','Integer',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','Model','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','Protocol','Integer',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','LastSentCommand','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','Level','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DeviceType','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','Methods','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DeviceAddress','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','DeviceChangeEvents','Boolean',0,'TRUE',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK MULTILEVEL SWITCH (LEARN)','Debug','Boolean','TRUE',0,0);

CALL osae_sp_object_type_add ('TELLSTICK TEMPERATURE SENSOR','Temperature sensor','Tellstick','TEMPERATURE SENSOR',0,0,0,1);
CALL osae_sp_object_type_state_add('TELLSTICK TEMPERATURE SENSOR','ON','On');
CALL osae_sp_object_type_state_add('TELLSTICK TEMPERATURE SENSOR','OFF','Off');
CALL osae_sp_object_type_state_add('TELLSTICK TEMPERATURE SENSOR','DISABLE','Disabled');
CALL osae_sp_object_type_state_add('TELLSTICK TEMPERATURE SENSOR','UNKNOWN','Unknown');
CALL osae_sp_object_type_event_add('TELLSTICK TEMPERATURE SENSOR','TEMPERATURE','Temperature');
CALL osae_sp_object_type_event_add('TELLSTICK TEMPERATURE SENSOR','MAXTEMP','MaxTemp');
CALL osae_sp_object_type_event_add('TELLSTICK TEMPERATURE SENSOR','MINTEMP','MinTemp');
CALL osae_sp_object_type_event_add('TELLSTICK TEMPERATURE SENSOR','AVERAGETEMP','AverageTemp');
CALL osae_sp_object_type_method_add('TELLSTICK TEMPERATURE SENSOR','ENABLE','Enable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMPERATURE SENSOR','DISABLE','Disable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMPERATURE SENSOR','DEBUGON','Debug ON','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMPERATURE SENSOR','DEBUGOFF','Debug OFF','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMPERATURE SENSOR','RESETMAXMIN','Reset Max-Min','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMPERATURE SENSOR','RESTORE','Restore Object type','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','Temperature','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','Unit','String',0,'C',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','DeviceId','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','DeviceType','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','Model','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','Protocol','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','DeviceAddress','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','OFF TIMER','Integer',0,'600',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','Debug','Boolean',0,'TRUE',0);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','AverageTemp','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','MinTemp','Float',0,'255',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMPERATURE SENSOR','MaxTemp','Float',0,'-255',1);

CALL osae_sp_object_type_add ('TELLSTICK TEMP-HUMIDITY SENSOR','Temperature & humidity sensor','Tellstick','TEMP HUM METER',0,0,0,1);
CALL osae_sp_object_type_state_add('TELLSTICK TEMP-HUMIDITY SENSOR','DISABLE','Disabled');
CALL osae_sp_object_type_state_add('TELLSTICK TEMP-HUMIDITY SENSOR','ON','On');
CALL osae_sp_object_type_state_add('TELLSTICK TEMP-HUMIDITY SENSOR','OFF','Off');
CALL osae_sp_object_type_state_add('TELLSTICK TEMP-HUMIDITY SENSOR','UNKNOWN','Unknown');
CALL osae_sp_object_type_event_add('TELLSTICK TEMP-HUMIDITY SENSOR','TEMPERATURE','Temperature');
CALL osae_sp_object_type_event_add('TELLSTICK TEMP-HUMIDITY SENSOR','HUMIDITY','Humidity');
CALL osae_sp_object_type_event_add('TELLSTICK TEMP-HUMIDITY SENSOR','AVERAGEHUM','AverageHum');
CALL osae_sp_object_type_event_add('TELLSTICK TEMP-HUMIDITY SENSOR','AVERAGETEMP','AverageTemp');
CALL osae_sp_object_type_event_add('TELLSTICK TEMP-HUMIDITY SENSOR','MAXTEMP','MaxTemp');
CALL osae_sp_object_type_event_add('TELLSTICK TEMP-HUMIDITY SENSOR','MINTEMP','MinTemp');
CALL osae_sp_object_type_event_add('TELLSTICK TEMP-HUMIDITY SENSOR','MINHUM','MinHum');
CALL osae_sp_object_type_event_add('TELLSTICK TEMP-HUMIDITY SENSOR','MAXHUM','MaxHum');
CALL osae_sp_object_type_method_add('TELLSTICK TEMP-HUMIDITY SENSOR','DISABLE','Disable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMP-HUMIDITY SENSOR','ENABLE','Enable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMP-HUMIDITY SENSOR','DEBUGOFF','Debug OFF','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMP-HUMIDITY SENSOR','DEBUGON','Debug ON','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMP-HUMIDITY SENSOR','RESETMAXMIN','Reset Max-Min','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK TEMP-HUMIDITY SENSOR','RESTORE','Restore Object type','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','DeviceAddress','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','DeviceId','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','DeviceType','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','Model','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','Protocol','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','Temperature','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','Unit','String',0,'C',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','Humidity','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','OFF TIMER','Integer',0,'600',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','Status','String',0,'Not Implemented',0);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','Battery','String',0,'Not Implemented',0);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','Debug','Boolean',0,'TRUE',0);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','AverageTemp','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','AverageHum','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','MinHum','Float',0,'100',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','MaxHum','Float',0,'0',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','MaxTemp','Float',0,'-255',1);
CALL osae_sp_object_type_property_add('TELLSTICK TEMP-HUMIDITY SENSOR','MinTemp','Float',0,'255',1);

CALL osae_sp_object_type_add ('TELLSTICK UP-DOWN DEVICE','UP-DOWN Device on Tellstick Plugin','Tellstick','UP-DOWN DEVICE',1,1,0,1);
CALL osae_sp_object_type_state_add('TELLSTICK UP-DOWN DEVICE','OFF','Off');
CALL osae_sp_object_type_state_add('TELLSTICK UP-DOWN DEVICE','ON','On');
CALL osae_sp_object_type_state_add('TELLSTICK UP-DOWN DEVICE','DISABLE','Disabled');
CALL osae_sp_object_type_state_add('TELLSTICK UP-DOWN DEVICE','UNKNOWN','Unknown');
CALL osae_sp_object_type_event_add('TELLSTICK UP-DOWN DEVICE','STOP','Stop');
CALL osae_sp_object_type_event_add('TELLSTICK UP-DOWN DEVICE','UP','Up');
CALL osae_sp_object_type_event_add('TELLSTICK UP-DOWN DEVICE','DOWN','Down');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','UP','Up','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','DOWN','Down','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','STOP','Stop','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','DISABLE','Disable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','ENABLE','Enable','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','LEARN','Learn','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','DEBUGON','Debug ON','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','DEBUGOFF','Debug OFF','','','','');
CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE','RESTORE','Restore Object type','','','','');
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','DeviceId','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','Model','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','Protocol','Integer',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','LastSentCommand','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','Level','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','DeviceType','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','Methods','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','DeviceAddress','String',0,'',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','DeviceChangeEvents','Boolean',0,'TRUE',1);
CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE','Debug','Boolean',0,'TRUE',0);

-- CALL osae_sp_object_type_add ('TELLSTICK UP-DOWN DEVICE (LEARN)','UP-DOWN Device on Tellstick Plugin','Tellstick','UP-DOWN DEVICE',1,1,0,1);
-- CALL osae_sp_object_type_state_add('TELLSTICK UP-DOWN DEVICE (LEARN)','OFF','Off');
-- CALL osae_sp_object_type_state_add('TELLSTICK UP-DOWN DEVICE (LEARN)','ON','On');
-- CALL osae_sp_object_type_state_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DISABLE','Disabled');
-- CALL osae_sp_object_type_state_add('TELLSTICK UP-DOWN DEVICE (LEARN)','UNKNOWN','Unknown');
-- CALL osae_sp_object_type_event_add('TELLSTICK UP-DOWN DEVICE (LEARN)','STOP','Stop');
-- CALL osae_sp_object_type_event_add('TELLSTICK UP-DOWN DEVICE (LEARN)','UP','Up');
-- CALL osae_sp_object_type_event_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DOWN','Down');
-- CALL osae_sp_object_type_event_add('TELLSTICK UP-DOWN DEVICE (LEARN)','LEARN','Learn');
-- CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE (LEARN)','UP','Up','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DOWN','Down','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE (LEARN)','STOP','Stop','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DISABLE','Disable','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE (LEARN)','ENABLE','Enable','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE (LEARN)','LEARN','Learn','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DEBUGON','Debug ON','','','','');
-- CALL osae_sp_object_type_method_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DEBUGOFF','Debug OFF','','','','');
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DeviceId','Integer',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','Model','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','Protocol','Integer',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','LastSentCommand','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','Level','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DeviceType','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','Methods','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DeviceAddress','String',0,'',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','DeviceChangeEvents','Boolean',0,'TRUE',1);
-- CALL osae_sp_object_type_property_add('TELLSTICK UP-DOWN DEVICE (LEARN)','Debug','Boolean',0,'TRUE',0);
