CALL osae_sp_object_type_add ('CM11A','X10 Plugin Class','','PLUGIN',1,0,0,1,'X-10 CM11 plugin.');
CALL osae_sp_object_type_state_add('CM11A','ON','Running','The CM11A plugin is running.');
CALL osae_sp_object_type_state_add('CM11A','OFF','Stopped','The CM11A plugin is Stopped.');
CALL osae_sp_object_type_event_add('CM11A','ON','Started','The CM11A plugin Started.');
CALL osae_sp_object_type_event_add('CM11A','OFF','Stopped','The CM11A plugin Stopped.');
CALL osae_sp_object_type_method_add('CM11A','ON','Start','','','','','Start the Bluetooth plugin.');
CALL osae_sp_object_type_method_add('CM11A','OFF','Stop','','','','','Stop the CM11A plugin.');
CALL osae_sp_object_type_method_add('CM11A','CLEAR','Clear CM11A Memory','','','','','Clear all stored memory in the CM11A.');
CALL osae_sp_object_type_method_add('CM11A','RESET','Reset the CM11A','','','','','Reset the CM11A controller..');
CALL osae_sp_object_type_method_add('CM11A','SET POLL RATE','Set CM11a Poll Rate','Rate in ms','','30000','','Set the CM11A Poll Rate.');
CALL osae_sp_object_type_method_add('CM11A','SET LEARNING MODE','Set Learning Mode','TRUE/FALSE','','TRUE','','Set the CM11A Learning Mode.');
CALL osae_sp_object_type_property_add('CM11A','Port','Integer','','0',0,1,'Serial Port number for the CM11A controller.');
CALL osae_sp_object_type_property_add('CM11A','Poll Rate','Integer','','120',0,1,'Number of seconds that the CM11A will Poll for status.');
CALL osae_sp_object_type_property_add('CM11A','Learning Mode','Boolean','','TRUE',0,0,'Is the CM11A plugin in Learning Mode?');
CALL osae_sp_object_type_property_add('CM11A','System Plugin','Boolean','','FALSE',0,0,'Is the CM11A Plugin is a system plugin?');
CALL osae_sp_object_type_property_add('CM11A','Trust Level','Integer','','90',0,1,'CM11A plugin Trust Level');
CALL osae_sp_object_type_property_add('CM11A','Version','String','','',0,1,'Version of the CM11A plugin');
CALL osae_sp_object_type_property_add('CM11A','Author','String','','',0,1,'Author of the CM11A plugin');

CALL osae_sp_object_type_add ('X10 DIMMER','X10 Dimmer','','SWITCH',0,0,0,0,'X10 Dimmer');
CALL osae_sp_object_type_state_add('X10 DIMMER','ON','On','On');
CALL osae_sp_object_type_state_add('X10 DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 DIMMER','ON','On','On');
CALL osae_sp_object_type_event_add('X10 DIMMER','OFF','Off','Off');
CALL osae_sp_object_type_method_add('X10 DIMMER','ON','On','Dim Level in %','','100','','Turn On');
CALL osae_sp_object_type_method_add('X10 DIMMER','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_method_add('X10 DIMMER','BRIGHT','Bright','Increment %','','10','','Bright');
CALL osae_sp_object_type_method_add('X10 DIMMER','DIM','Dim','Decrement %','','10','','Dim');
CALL osae_sp_object_type_property_add('X10 DIMMER','Off Timer','Integer','','-1',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('X10 DIMMER','Level','Integer','','0',0,0,'Dim Level 0-100%');
CALL osae_sp_object_type_property_add('X10 DIMMER','Soft Start','Boolean','','FALSE',0,0,'Soft Start');

CALL osae_sp_object_type_add ('X10 RELAY','X10 Relay','','SWITCH',0,0,0,0,'X10 Relay');
CALL osae_sp_object_type_state_add('X10 RELAY','ON','On','On');
CALL osae_sp_object_type_state_add('X10 RELAY','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 RELAY','ON','On','On');
CALL osae_sp_object_type_event_add('X10 RELAY','OFF','Off','Off');
CALL osae_sp_object_type_method_add('X10 RELAY','ON','On','','','','','Turn On');
CALL osae_sp_object_type_method_add('X10 RELAY','OFF','Off','','','','','Turn Off');
CALL osae_sp_object_type_property_add('X10 RELAY','Off Timer','Integer','','-1',0,1,'# of seconds after activity until device turns off');
CALL osae_sp_object_type_property_add('X10 RELAY','Soft Start','Boolean','','FALSE',0,0,'Soft Start');

CALL osae_sp_object_type_add ('X10 SENSOR','X10 Sensor','','SENSOR',0,0,0,0,'X10 Sensor');
CALL osae_sp_object_type_state_add('X10 SENSOR','ON','On','On');
CALL osae_sp_object_type_state_add('X10 SENSOR','OFF','Off','Off');
CALL osae_sp_object_type_event_add('X10 SENSOR','ON','On','On');
CALL osae_sp_object_type_event_add('X10 SENSOR','OFF','Off','Off');
CALL osae_sp_object_type_property_add('X10 SENSOR','Off Timer','Integer','','-1',0,1,'Off Timer');
CALL osae_sp_object_type_property_add('X10 SENSOR','Level','Integer','','0',0,0,'Level');

CALL osae_sp_object_type_add ('X10 PHOTOCELL','X10 Photocell','','SENSOR',0,0,0,0,'X10 Photocell');
CALL osae_sp_object_type_state_add('X10 PHOTOCELL','ON','Dark','Dark');
CALL osae_sp_object_type_state_add('X10 PHOTOCELL','OFF','Light','Light');
CALL osae_sp_object_type_event_add('X10 PHOTOCELL','ON','Dark','Dark');
CALL osae_sp_object_type_event_add('X10 PHOTOCELL','OFF','Light','Light');
CALL osae_sp_object_type_property_add('X10 PHOTOCELL','Off Timer','Integer','','-1',0,1,'Off Timer');
CALL osae_sp_object_type_property_add('X10 PHOTOCELL','Level','Integer','','0',1,'Level');