//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager_WPF.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IWCFService", CallbackContract=typeof(Manager_WPF.WCFService.IWCFServiceCallback))]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SendMessageToClients", ReplyAction="http://tempuri.org/IWCFService/SendMessageToClientsResponse")]
        void SendMessageToClients(string msgType, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/Subscribe", ReplyAction="http://tempuri.org/IWCFService/SubscribeResponse")]
        bool Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/Unsubscribe", ReplyAction="http://tempuri.org/IWCFService/UnsubscribeResponse")]
        bool Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/messageHost", ReplyAction="http://tempuri.org/IWCFService/messageHostResponse")]
        void messageHost(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetAllObjects", ReplyAction="http://tempuri.org/IWCFService/GetAllObjectsResponse")]
        OSAE.OSAEObject[] GetAllObjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetObject", ReplyAction="http://tempuri.org/IWCFService/GetObjectResponse")]
        OSAE.OSAEObject GetObject(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetObjectByAddress", ReplyAction="http://tempuri.org/IWCFService/GetObjectByAddressResponse")]
        OSAE.OSAEObject GetObjectByAddress(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ExecuteMethod", ReplyAction="http://tempuri.org/IWCFService/ExecuteMethodResponse")]
        bool ExecuteMethod(string name, string method, string param1, string param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddObject", ReplyAction="http://tempuri.org/IWCFService/AddObjectResponse")]
        bool AddObject(string name, string description, string type, string address, string container, string enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/UpdateObject", ReplyAction="http://tempuri.org/IWCFService/UpdateObjectResponse")]
        bool UpdateObject(string oldName, string newName, string description, string type, string address, string container, int enabled);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/DeleteObject", ReplyAction="http://tempuri.org/IWCFService/DeleteObjectResponse")]
        bool DeleteObject(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetObjectsByType", ReplyAction="http://tempuri.org/IWCFService/GetObjectsByTypeResponse")]
        OSAE.OSAEObject[] GetObjectsByType(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetObjectsByBaseType", ReplyAction="http://tempuri.org/IWCFService/GetObjectsByBaseTypeResponse")]
        OSAE.OSAEObject[] GetObjectsByBaseType(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetObjectsByContainer", ReplyAction="http://tempuri.org/IWCFService/GetObjectsByContainerResponse")]
        OSAE.OSAEObject[] GetObjectsByContainer(string container);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetPlugins", ReplyAction="http://tempuri.org/IWCFService/GetPluginsResponse")]
        OSAE.OSAEObject[] GetPlugins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SendPattern", ReplyAction="http://tempuri.org/IWCFService/SendPatternResponse")]
        bool SendPattern(string pattern);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddScript", ReplyAction="http://tempuri.org/IWCFService/AddScriptResponse")]
        bool AddScript(string objName, string objEvent, string script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/UpdateScript", ReplyAction="http://tempuri.org/IWCFService/UpdateScriptResponse")]
        bool UpdateScript(string objName, string objEvent, string script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/ExecuteSQL", ReplyAction="http://tempuri.org/IWCFService/ExecuteSQLResponse")]
        System.Data.DataSet ExecuteSQL(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SetProperty", ReplyAction="http://tempuri.org/IWCFService/SetPropertyResponse")]
        bool SetProperty(string objName, string propName, string propValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/SetState", ReplyAction="http://tempuri.org/IWCFService/SetStateResponse")]
        bool SetState(string objName, string state);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IWCFService/OnMessageReceived")]
        void OnMessageReceived(string msgType, string message, System.DateTime timestamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : Manager_WPF.WCFService.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.DuplexClientBase<Manager_WPF.WCFService.IWCFService>, Manager_WPF.WCFService.IWCFService {
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendMessageToClients(string msgType, string message) {
            base.Channel.SendMessageToClients(msgType, message);
        }
        
        public bool Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public bool Unsubscribe() {
            return base.Channel.Unsubscribe();
        }
        
        public void messageHost(string message) {
            base.Channel.messageHost(message);
        }
        
        public OSAE.OSAEObject[] GetAllObjects() {
            return base.Channel.GetAllObjects();
        }
        
        public OSAE.OSAEObject GetObject(string name) {
            return base.Channel.GetObject(name);
        }
        
        public OSAE.OSAEObject GetObjectByAddress(string address) {
            return base.Channel.GetObjectByAddress(address);
        }
        
        public bool ExecuteMethod(string name, string method, string param1, string param2) {
            return base.Channel.ExecuteMethod(name, method, param1, param2);
        }
        
        public bool AddObject(string name, string description, string type, string address, string container, string enabled) {
            return base.Channel.AddObject(name, description, type, address, container, enabled);
        }
        
        public bool UpdateObject(string oldName, string newName, string description, string type, string address, string container, int enabled) {
            return base.Channel.UpdateObject(oldName, newName, description, type, address, container, enabled);
        }
        
        public bool DeleteObject(string name) {
            return base.Channel.DeleteObject(name);
        }
        
        public OSAE.OSAEObject[] GetObjectsByType(string type) {
            return base.Channel.GetObjectsByType(type);
        }
        
        public OSAE.OSAEObject[] GetObjectsByBaseType(string type) {
            return base.Channel.GetObjectsByBaseType(type);
        }
        
        public OSAE.OSAEObject[] GetObjectsByContainer(string container) {
            return base.Channel.GetObjectsByContainer(container);
        }
        
        public OSAE.OSAEObject[] GetPlugins() {
            return base.Channel.GetPlugins();
        }
        
        public bool SendPattern(string pattern) {
            return base.Channel.SendPattern(pattern);
        }
        
        public bool AddScript(string objName, string objEvent, string script) {
            return base.Channel.AddScript(objName, objEvent, script);
        }
        
        public bool UpdateScript(string objName, string objEvent, string script) {
            return base.Channel.UpdateScript(objName, objEvent, script);
        }
        
        public System.Data.DataSet ExecuteSQL(string sql) {
            return base.Channel.ExecuteSQL(sql);
        }
        
        public bool SetProperty(string objName, string propName, string propValue) {
            return base.Channel.SetProperty(objName, propName, propValue);
        }
        
        public bool SetState(string objName, string state) {
            return base.Channel.SetState(objName, state);
        }
    }
}
