CALL osae_sp_object_type_add ('PHIDGET-SERVO','Phidget Servo Controller','','PLUGIN',1,1,0,1,'Phidget Servo Controller');
CALL osae_sp_object_type_state_add ('PHIDGET-SERVO','ON','Running','The Phidget Servo plugin is Running');
CALL osae_sp_object_type_state_add ('PHIDGET-SERVO','OFF','Stopped','The Phidget Servo plugin is Stopped!');
CALL osae_sp_object_type_event_add ('PHIDGET-SERVO','ON','Started','The Phidget Servo plugin was Started');
CALL osae_sp_object_type_event_add ('PHIDGET-SERVO','OFF','Stopped','The Phidget Servo plugin was Stopped!');
CALL osae_sp_object_type_method_add ('PHIDGET-SERVO','ON','Start','','','','','Start the Phidget Servo plugin');
CALL osae_sp_object_type_method_add ('PHIDGET-SERVO','OFF','Stop','','','','','Stop the Phidget Servo plugin');
CALL osae_sp_object_type_property_add ('PHIDGET-SERVO','Attached','Boolean','','FALSE',0,1,'Is the Phidget Servo board Attached');
CALL osae_sp_object_type_property_add ('PHIDGET-SERVO','Serial','String','','',0,0,'Phidget Servo board Serial Number');
CALL osae_sp_object_type_property_add ('PHIDGET-SERVO','Position','Integer','','0',0,0,'Phidget Servo Position');
CALL osae_sp_object_type_property_add ('PHIDGET-SERVO','Default Position','Integer','','0',0,0,'Phidget Servo Default Position');
CALL osae_sp_object_type_property_add('PHIDGET-SERVO','Trust Level','Integer','','90',0,1,'Phidget Servo board Trust Level');
CALL osae_sp_object_type_property_add('PHIDGET-SERVO','Version','String','','',0,1,'Phidget Servo plugin Version');
CALL osae_sp_object_type_property_add('PHIDGET-SERVO','Author','String','','',0,1,'Phidget Servo plugin written by');

CALL osae_sp_object_type_add ('PHIDGET SERVO','Phidget Servo','','THING',0,0,0,0,'Phidget Servo');
CALL osae_sp_object_type_method_add('PHIDGET SERVO','POSITION','Set Position','Position','','','','Set Servo Position');
CALL osae_sp_object_type_method_add('PHIDGET SERVO','ENGAGE','Engage Servo','','','','','Engage Servo');
CALL osae_sp_object_type_method_add('PHIDGET SERVO','DISENGAGE','Disengage Servo','','','','','Disengage Servo');
CALL osae_sp_object_type_property_add('PHIDGET SERVO','Default Position','Integer','','0',0,0,'Default Position');
CALL osae_sp_object_type_property_add('PHIDGET SERVO','Position','Integer','','0',0,0,'Position');
CALL osae_sp_object_type_property_add('PHIDGET SERVO','Min Position','Integer','','0',0,0,'Min Position');
CALL osae_sp_object_type_property_add('PHIDGET SERVO','Max Position','Integer','','0',0,0,'Max Position');