CALL osae_sp_object_type_add ('PHIDGET-SERVO','Phidget Servo Controller','','PLUGIN',1,1,0,1);
CALL osae_sp_object_type_state_add ('ON','Running','PHIDGET-SERVO');
CALL osae_sp_object_type_state_add ('OFF','Stopped','PHIDGET-SERVO');
CALL osae_sp_object_type_event_add ('ON','Started','PHIDGET-SERVO');
CALL osae_sp_object_type_event_add ('OFF','Stopped','PHIDGET-SERVO');
CALL osae_sp_object_type_method_add ('ON','Start','PHIDGET-SERVO','','','','');
CALL osae_sp_object_type_method_add ('OFF','Stop','PHIDGET-SERVO','','','','');
CALL osae_sp_object_type_property_add ('Attached','Boolean','','PHIDGET-SERVO',0);
CALL osae_sp_object_type_property_add ('Computer Name','String','','PHIDGET-SERVO',0);
CALL osae_sp_object_type_property_add ('Serial','String','','PHIDGET-SERVO',0);
CALL osae_sp_object_type_property_add ('Position','Integer','','PHIDGET-SERVO',0);
CALL osae_sp_object_type_property_add ('Default Position','Integer','','PHIDGET-SERVO',0);

CALL osae_sp_object_type_add ('PHIDGET SERVO','Phidget Servo','','THING',0,0,0,0);
CALL osae_sp_object_type_method_add('PHIDGET SERVO','POSITION','Set Position','Position','','','');
CALL osae_sp_object_type_method_add('PHIDGET SERVO','ENGAGE','Engage Servo','','','','');
CALL osae_sp_object_type_method_add('PHIDGET SERVO','DISENGAGE','Disengage Servo','','','','');
CALL osae_sp_object_type_property_add('PHIDGET SERVO','Default Position','Integer','0','',0);
CALL osae_sp_object_type_property_add('PHIDGET SERVO','Position','Integer','0','',0);
CALL osae_sp_object_type_property_add('PHIDGET SERVO','Min Position','Integer','0','',0);
CALL osae_sp_object_type_property_add('PHIDGET SERVO','Max Position','Integer','0','',0);